# Generated by Django 2.1.1 on 2019-02-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181209_0546'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='catrgory',
            field=models.CharField(default=2, max_length=20),
            preserve_default=False,
        ),
    ]
