# Generated by Django 2.1.1 on 2019-02-06 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190201_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='category',
        ),
    ]
