# Generated by Django 2.1.7 on 2019-03-05 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20190227_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='street_address_1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='street_address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
