# Generated by Django 2.1.7 on 2019-03-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20190306_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='street_address_2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
