# Generated by Django 2.1.7 on 2019-03-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20190312_2214'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('message', models.CharField(max_length=200)),
            ],
        ),
    ]
