# Generated by Django 2.1.1 on 2019-03-14 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20190313_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='referral_link',
            new_name='referral_id',
        ),
    ]
