# Generated by Django 2.1.1 on 2019-03-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_customuser_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reward_points',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
