# Generated by Django 2.1.1 on 2019-03-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_customuser_reward_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='reward_points',
            field=models.IntegerField(default=0),
        ),
    ]
