# Generated by Django 2.1.1 on 2019-03-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20190314_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_accept_points',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_award_points',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_limit',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referred_who',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
