# Generated by Django 2.1.1 on 2019-03-18 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_auto_20190314_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_award_points', models.IntegerField(default=5)),
                ('referral_accept_points', models.IntegerField(default=3)),
            ],
        ),
    ]
