# Generated by Django 2.1.1 on 2019-03-18 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_config_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='referral_limit',
            field=models.IntegerField(default=10),
        ),
    ]
