# Generated by Django 2.1.1 on 2019-03-18 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20190317_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_accept_points',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_award_points',
            field=models.IntegerField(default=5),
        ),
        migrations.AddField(
            model_name='customuser',
            name='referral_limit',
            field=models.IntegerField(default=10),
        ),
    ]
