# Generated by Django 2.1.1 on 2019-03-18 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20190317_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='referred_who',
        ),
        migrations.AddField(
            model_name='customuser',
            name='referred_who',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
