# Generated by Django 2.1.1 on 2019-03-20 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_remove_customuser_referred_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referred_who',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Referral'),
        ),
    ]
