# Generated by Django 2.1.7 on 2019-03-22 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_merge_20190321_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticemessage',
            name='message_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='noticemessage',
            name='message_zh',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='noticemessage',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
