# Generated by Django 2.1.1 on 2019-03-22 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_customuser_fund'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='fund',
            new_name='balance',
        ),
    ]
