# Generated by Django 2.1.7 on 2019-03-22 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20190322_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticemessage',
            name='message_fr',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='noticemessage',
            name='message_zh',
            field=models.CharField(default='', max_length=200),
        ),
    ]
