# Generated by Django 2.1.1 on 2019-03-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20190321_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='Referee_add_balance_reward',
            field=models.IntegerField(default=1),
        ),
    ]
