# Generated by Django 2.1.7 on 2019-03-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_auto_20190322_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticemessage',
            name='message',
            field=models.CharField(default='', max_length=200),
        ),
    ]
