# Generated by Django 2.1.1 on 2019-03-27 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_customuser_activation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referees', to=settings.AUTH_USER_MODEL),
        ),
    ]
