# Generated by Django 2.1.1 on 2019-03-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_auto_20190328_0033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='activation_Code',
            new_name='activation_code',
        ),
    ]
