# Generated by Django 2.1.7 on 2019-04-18 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0073_auto_20190405_1403'),
        ('users', '0068_auto_20190408_1117'),
    ]

    operations = [
    ]
