# Generated by Django 2.1.7 on 2019-04-15 18:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0068_usertag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('name_zh', models.CharField(blank=True, max_length=50, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(max_length=200)),
                ('parent_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_zh', models.CharField(blank=True, max_length=50, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Start Time')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='End Time')),
                ('opponent1', models.CharField(blank=True, max_length=200, null=True)),
                ('opponent2', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(max_length=200)),
                ('description_zh', models.CharField(blank=True, max_length=200, null=True)),
                ('description_fr', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, upload_to='game_image')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Category')),
                ('status_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_status', to='users.Status')),
            ],
        ),
    ]
