# Generated by Django 2.1.7 on 2019-04-19 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Game Category'},
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'verbose_name_plural': 'Game'},
        ),
    ]
