# Generated by Django 2.1.7 on 2019-05-23 05:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0088_merge_20190516_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('agent_id', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('agent_level', models.SmallIntegerField(choices=[(0, 'Promo Agent'), (1, 'Affliate'), (2, 'Primary Agent')], default=0, verbose_name='Agent Level')),
                ('active_user', models.IntegerField(default=0, verbose_name='Active User')),
                ('downline_deposit', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Downline Deposit')),
                ('turnover', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Turnover')),
                ('downline_ggr', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Downline GGR')),
                ('commission_last_month', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Last Month Commission')),
                ('commission_of_the_month_before', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Commission Of the Month Before')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agent',
            },
        ),
    ]
