# Generated by Django 2.1.7 on 2019-05-23 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='agent_id',
            new_name='username',
        ),
    ]
