# Generated by Django 2.1.7 on 2019-06-18 02:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0100_auto_20190614_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('commission_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('commission_set', models.CharField(choices=[('System', 'System'), ('Personal', 'Personal')], default='System', max_length=50, verbose_name='Commission_set')),
                ('commision_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Commision Percentage')),
                ('downline_commision_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Downline Commision Percentage')),
                ('commission_level', models.IntegerField(default=1)),
                ('active_downline_needed', models.IntegerField(default=6)),
                ('monthly_downline_ftd_needed', models.IntegerField(default=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='active_downline_needed',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='commision_percentage',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='commission_level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='commission_set',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='downline_commision_percentage',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='monthly_downline_ftd_needed',
        ),
    ]
