# Generated by Django 2.1.7 on 2019-06-18 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0101_auto_20190617_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='commission_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Commission', verbose_name='Commission'),
        ),
    ]
