# Generated by Django 2.1.7 on 2019-06-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0102_customuser_commission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='agent_level',
            field=models.CharField(choices=[('Affiliates', 'Affiliates'), ('Deactivated', 'Deactivated'), ('Refer a friend', 'Refer a friend'), ('Negative', 'Negative'), ('Internal affiliates', 'Internal affiliates')], max_length=50, null=True, verbose_name='Agent Level'),
        ),
    ]
