# Generated by Django 2.1.7 on 2019-04-18 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticemessage',
            options={'verbose_name_plural': 'Notice Message'},
        ),
    ]
