# Generated by Django 2.1.7 on 2019-06-07 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0002_auto_20190418_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='PushNoticeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField(verbose_name='Start Time')),
                ('end_time', models.DateField(verbose_name='End Time')),
                ('message', models.CharField(default='', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Push Notice Message',
            },
        ),
    ]
