# Generated by Django 2.1.7 on 2019-06-14 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0007_auto_20190614_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notifiers',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
