# Generated by Django 2.1.7 on 2019-03-05 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20190305_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='street_address_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='street_address_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
