# Generated by Django 2.1.7 on 2019-04-30 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_auto_20190429_0941'),
        ('users', '0080_auto_20190430_1152'),
    ]

    operations = [
    ]
