# Generated by Django 2.1.7 on 2019-05-06 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_auto_20190429_0957'),
        ('users', '0081_merge_20190430_1403'),
    ]

    operations = [
    ]
