# Generated by Django 2.1.7 on 2019-06-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0103_auto_20190625_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='risk_level',
            field=models.SmallIntegerField(choices=[(0, 'A'), (1, 'E1'), (2, 'E2'), (3, 'F')], default=0),
        ),
    ]
