# Generated by Django 2.1.7 on 2019-07-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0108_merge_20190626_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitation',
            name='interval',
            field=models.SmallIntegerField(choices=[(0, 'per day'), (1, 'per week'), (2, 'per month')], default=0, null=True),
        ),
    ]
