# Generated by Django 2.1.7 on 2019-05-02 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Amount')),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Request Time')),
                ('arrive_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Arrive Time')),
                ('status', models.SmallIntegerField(choices=[(0, 'Yes'), (1, 'No')], default=1)),
                ('channel', models.SmallIntegerField(choices=[(0, 'Alipay'), (1, 'Wechat'), (2, 'Card')], default=2, verbose_name='Channel')),
                ('transaction_type', models.SmallIntegerField(choices=[(0, 'Deposit'), (1, 'Withdraw')], default=0, verbose_name='Transaction Type')),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'transaction',
                'verbose_name_plural': 'transaction',
            },
        ),
    ]
