# Generated by Django 2.1.7 on 2019-05-07 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThirdParty',
            fields=[
                ('thridParty_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thridParty_name', models.SmallIntegerField(choices=[(0, 'Alipay'), (1, 'Wechat'), (2, 'Card')], default=2, verbose_name='Name')),
                ('currency', models.SmallIntegerField(choices=[(0, 'CNY'), (1, 'USD'), (2, 'PHP')], default=0, verbose_name='Currency')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Min Amount')),
                ('max_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Max Amount')),
                ('transaction_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Transaction Fee')),
                ('switch', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'ThirdParty',
                'verbose_name_plural': 'ThirdParty',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Amount')),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Request Time')),
                ('arrive_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Arrive Time')),
                ('status', models.SmallIntegerField(choices=[(0, 'Success'), (1, 'Unsuccess')], default=1)),
                ('channel', models.SmallIntegerField(choices=[(0, 'Alipay'), (1, 'Wechat'), (2, 'Card')], default=2, verbose_name='Channel')),
                ('transaction_type', models.SmallIntegerField(choices=[(0, 'Deposit'), (1, 'Withdraw')], default=0, verbose_name='Transaction Type')),
                ('remark', models.CharField(blank=True, max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transaction',
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('accounting.transaction',),
        ),
    ]
