# Generated by Django 2.1.7 on 2019-05-02 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(choices=[(0, 'pending'), (1, 'approved')], default=0, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Deposit',
                'verbose_name_plural': 'Deposit Review',
            },
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Transaction', 'verbose_name_plural': 'Transaction'},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Success'), (1, 'Unsuccess')], default=1),
        ),
        migrations.AddField(
            model_name='depositreview',
            name='deposit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Transaction', verbose_name='Deposit id'),
        ),
        migrations.AddField(
            model_name='depositreview',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='depositreview',
            unique_together={('deposit_id', 'user_id')},
        ),
    ]
