# Generated by Django 2.1.7 on 2019-05-07 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Deposit',
        ),
    ]
