# Generated by Django 2.1.7 on 2019-05-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdraw',
            fields=[
            ],
            options={
                'verbose_name': 'Withdraw Review',
                'verbose_name_plural': 'Withdraw Review',
                'proxy': True,
                'indexes': [],
            },
            bases=('accounting.transaction',),
        ),
        migrations.AlterModelOptions(
            name='deposit',
            options={'verbose_name': 'Deposit Review', 'verbose_name_plural': 'Deposit Review'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='review_status',
            field=models.SmallIntegerField(choices=[(0, 'Approved'), (1, 'Pending'), (2, 'Rejected')], default=1, verbose_name='Review status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='remark',
            field=models.CharField(blank=True, max_length=200, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Success'), (1, 'Unsuccess')], default=1, verbose_name='Status'),
        ),
    ]
