# Generated by Django 2.1.7 on 2019-05-13 06:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20190510_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositChannel',
            fields=[
                ('thridParty_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thridParty_name', models.SmallIntegerField(choices=[(0, 'Alipay'), (1, 'Wechat'), (2, 'Card'), (3, 'Qaicash'), (4, 'Asia Pay')], default=2, verbose_name='Name')),
                ('currency', models.SmallIntegerField(choices=[(0, 'CNY'), (1, 'USD'), (2, 'PHP')], default=0, verbose_name='Currency')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Min Amount')),
                ('max_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Max Amount')),
                ('switch', models.BooleanField(default=True, verbose_name='Active')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
            ],
            options={
                'verbose_name': 'Deposit Channel',
                'verbose_name_plural': 'Deposit Channel',
            },
        ),
        migrations.CreateModel(
            name='WithdrawChannel',
            fields=[
                ('thridParty_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thridParty_name', models.SmallIntegerField(choices=[(0, 'Alipay'), (1, 'Wechat'), (2, 'Card'), (3, 'Qaicash'), (4, 'Asia Pay')], default=2, verbose_name='Name')),
                ('currency', models.SmallIntegerField(choices=[(0, 'CNY'), (1, 'USD'), (2, 'PHP')], default=0, verbose_name='Currency')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Min Amount')),
                ('max_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Max Amount')),
                ('switch', models.BooleanField(default=True, verbose_name='Active')),
                ('transaction_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Transaction Fee')),
            ],
            options={
                'verbose_name': 'Withdraw Channel',
                'verbose_name_plural': 'Withdraw Channel',
            },
        ),
        migrations.DeleteModel(
            name='ThirdParty',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.DeleteModel(
            name='Withdraw',
        ),
        migrations.CreateModel(
            name='DepositReview',
            fields=[
            ],
            options={
                'verbose_name': 'Deposit Review',
                'verbose_name_plural': 'Deposit Review',
                'proxy': True,
                'indexes': [],
            },
            bases=('accounting.transaction',),
        ),
        migrations.CreateModel(
            name='WithdrawReview',
            fields=[
            ],
            options={
                'verbose_name': 'Withdraw Review',
                'verbose_name_plural': 'Withdraw Review',
                'proxy': True,
                'indexes': [],
            },
            bases=('accounting.transaction',),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='channel',
            field=models.SmallIntegerField(choices=[(0, 'Alipay'), (1, 'Wechat'), (2, 'Card'), (3, 'Qaicash'), (4, 'Asia Pay')], default=2, verbose_name='Channel'),
        ),
    ]
