# Generated by Django 2.1.7 on 2019-05-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_delete_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='remark',
            field=models.CharField(blank=True, max_length=200, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Success'), (1, 'Unsuccess')], default=1, verbose_name='Status'),
        ),
    ]
