# Generated by Django 2.1.7 on 2019-05-21 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0007_auto_20190520_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='Method',
            field=models.CharField(blank=True, max_length=200, verbose_name='Method'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='depositorTier',
            field=models.SmallIntegerField(default=0, verbose_name='Depositor Tier'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='language',
            field=models.CharField(choices=[('en-Us', 'English – United States'), ('zh-Hans', 'Chinese Simplified'), ('th', 'Thai'), ('vi', 'Vietnamese'), ('ko', 'Korean'), ('ja', 'Japanese')], default='en-Us', max_length=20, verbose_name='Language'),
        ),
    ]
