# Generated by Django 2.1.7 on 2019-05-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20190521_1216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Method',
            new_name='method',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'SUCCESS'), (1, 'FAILED'), (2, 'PENDING'), (3, 'APPROVED'), (4, 'REJECTED')], default=1, verbose_name='Status'),
        ),
    ]
