# Generated by Django 2.1.7 on 2019-05-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_auto_20190521_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='Method',
        ),
        migrations.AddField(
            model_name='transaction',
            name='method',
            field=models.CharField(blank=True, max_length=200, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'SUCCESS'), (1, 'FAILED'), (2, 'PENDING'), (3, 'APPROVED'), (4, 'REJECTED')], default=1, verbose_name='Status'),
        ),
    ]
