# Generated by Django 2.1.7 on 2019-06-09 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20190523_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bank'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.SmallIntegerField(choices=[(0, 'Sports'), (1, 'Games'), (2, 'Live Casino'), (3, 'Financial'), (4, 'General')], default=4, verbose_name='Product'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_from',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='From'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transfer_to',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='To'),
        ),
        migrations.AlterField(
            model_name='depositchannel',
            name='thridParty_name',
            field=models.SmallIntegerField(choices=[(0, 'Alipay'), (1, 'Wechat'), (2, 'Card'), (3, 'Qaicash'), (4, 'Asia Pay'), (5, 'Paypal')], default=2, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Apply Amount'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='arrive_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Account Time'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='channel',
            field=models.SmallIntegerField(choices=[(0, 'Alipay'), (1, 'Wechat'), (2, 'Card'), (3, 'Qaicash'), (4, 'Asia Pay'), (5, 'Paypal')], default=2, verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(default=0, max_length=100, verbose_name='Transaction Code'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='remark',
            field=models.CharField(blank=True, max_length=200, verbose_name='Memo'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='request_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time of Application'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Transaction number'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.SmallIntegerField(choices=[(0, 'Deposit'), (1, 'Withdrawal'), (2, 'Bet Placed'), (3, 'Bet Settled'), (4, 'Transfer In'), (5, 'Transfer Out'), (6, 'Bonus'), (7, 'Adjustment'), (8, 'Commission')], default=0, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Member'),
        ),
        migrations.AlterField(
            model_name='withdrawchannel',
            name='thridParty_name',
            field=models.SmallIntegerField(choices=[(0, 'Alipay'), (1, 'Wechat'), (2, 'Card'), (3, 'Qaicash'), (4, 'Asia Pay'), (5, 'Paypal')], default=2, verbose_name='Name'),
        ),
    ]
