# Generated by Django 2.1.7 on 2019-06-06 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0013_merge_20190531_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositchannel',
            name='thridParty_name',
            field=models.SmallIntegerField(choices=[(0, 'Alipay'), (1, 'Wechat'), (2, 'Card'), (3, 'Qaicash'), (4, 'Asia Pay'), (5, 'Paypal')], default=2, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='channel',
            field=models.SmallIntegerField(choices=[(0, 'Alipay'), (1, 'Wechat'), (2, 'Card'), (3, 'Qaicash'), (4, 'Asia Pay'), (5, 'Paypal')], default=2, verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.SmallIntegerField(choices=[(0, 'Deposit'), (1, 'Withdrawal'), (2, 'Bet Placed'), (3, 'Bet Settled'), (4, 'Transfer In'), (5, 'Transfer Out'), (6, 'Bonus'), (7, 'Adjustment')], default=0, verbose_name='Transaction Type'),
        ),
        migrations.AlterField(
            model_name='withdrawchannel',
            name='thridParty_name',
            field=models.SmallIntegerField(choices=[(0, 'Alipay'), (1, 'Wechat'), (2, 'Card'), (3, 'Qaicash'), (4, 'Asia Pay'), (5, 'Paypal')], default=2, verbose_name='Name'),
        ),
    ]
