# Generated by Django 2.1.7 on 2019-06-07 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_auto_20190603_1155'),
        ('accounting', '0015_auto_20190605_1750'),
    ]

    operations = [
    ]
