# Generated by Django 2.1.7 on 2019-06-10 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_auto_20190606_1151'),
        ('accounting', '0017_auto_20190610_1019'),
    ]

    operations = [
    ]
