# Generated by Django 2.1.7 on 2019-06-21 19:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_auto_20190621_1220'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='transaction',
        #     name='trans_id',
        #     field=models.CharField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='#'),
        # ),
    ]
