# Generated by Django 2.1.7 on 2019-06-25 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_merge_20190624_1459'),
        ('accounting', '0032_merge_20190621_1803'),
    ]

    operations = [
    ]
