# Generated by Django 2.1.7 on 2019-06-25 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_transaction_last_updated'),
        ('accounting', '0032_merge_20190624_1459'),
    ]

    operations = [
    ]
