# Generated by Django 2.1.7 on 2019-07-08 22:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_auto_20190625_0042'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=0, max_length=200)),
                ('branch', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('city', models.CharField(blank=True, default=0, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='depositchannel',
            name='transaction_fee',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payer_id',
        ),
        migrations.AddField(
            model_name='depositchannel',
            name='new_user_volume',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=20),
        ),
        migrations.AddField(
            model_name='depositchannel',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Status Last Updated'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='new_user_volume',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=20),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=20),
        ),
        migrations.AlterField(
            model_name='depositchannel',
            name='switch',
            field=models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Disabled')], default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'SUCCESS'), (1, 'FAILED'), (2, 'CREATED'), (3, 'PENDING'), (4, 'APPROVED'), (5, 'CANCELED'), (6, 'COMPLETED')], default=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='withdrawchannel',
            name='switch',
            field=models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Disabled')], default=0),
        ),
        migrations.AddField(
            model_name='depositchannel',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Bank'),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='bank',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Bank'),
        ),
    ]
