# Generated by Django 2.1.7 on 2019-07-15 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0040_auto_20190709_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositchannel',
            name='currency',
            field=models.SmallIntegerField(choices=[(0, 'CNY'), (1, 'USD'), (2, 'THB'), (3, 'IDR'), (4, 'HKD'), (5, 'AUD'), (6, 'THB'), (7, 'MYR'), (8, 'VND'), (9, 'MMK'), (10, 'XBT')], default=0, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='depositchannel',
            name='thridParty_name',
            field=models.SmallIntegerField(choices=[(0, 'Help2pay'), (1, 'LINEpay'), (2, 'Astropay'), (3, 'Qaicash'), (4, 'Asia Pay'), (5, 'Paypal')], default=2, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='channel',
            field=models.SmallIntegerField(choices=[(0, 'Help2pay'), (1, 'LINEpay'), (2, 'Astropay'), (3, 'Qaicash'), (4, 'Asia Pay'), (5, 'Paypal')], default=0, verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.SmallIntegerField(choices=[(0, 'CNY'), (1, 'USD'), (2, 'THB'), (3, 'IDR'), (4, 'HKD'), (5, 'AUD'), (6, 'THB'), (7, 'MYR'), (8, 'VND'), (9, 'MMK'), (10, 'XBT')], verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'SUCCESS'), (1, 'FAILED'), (2, 'CREATED'), (3, 'PENDING'), (4, 'APPROVED'), (5, 'CANCELED'), (6, 'COMPLETED'), (7, 'RESEND'), (8, 'REJECTED')], default=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='withdrawchannel',
            name='currency',
            field=models.SmallIntegerField(choices=[(0, 'CNY'), (1, 'USD'), (2, 'THB'), (3, 'IDR'), (4, 'HKD'), (5, 'AUD'), (6, 'THB'), (7, 'MYR'), (8, 'VND'), (9, 'MMK'), (10, 'XBT')], default=0, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='withdrawchannel',
            name='thridParty_name',
            field=models.SmallIntegerField(choices=[(0, 'Help2pay'), (1, 'LINEpay'), (2, 'Astropay'), (3, 'Qaicash'), (4, 'Asia Pay'), (5, 'Paypal')], default=2, verbose_name='Name'),
        ),
    ]
