# Generated by Django 2.1.7 on 2019-07-31 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_usergroup_approvals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='approvals',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='system.UserGroup'),
        ),
    ]
