# Generated by Django 2.1.7 on 2019-09-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20190915_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='active_from',
            field=models.DateField(blank=True, null=True, verbose_name='Active From'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='active_to',
            field=models.DateField(blank=True, null=True, verbose_name='Register From'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='product',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='register_from',
            field=models.DateField(blank=True, null=True, verbose_name='Register From'),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='register_to',
            field=models.DateField(blank=True, null=True, verbose_name='Register From'),
        ),
    ]
