# Generated by Django 2.1.7 on 2019-09-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20190919_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='active_to',
            field=models.DateField(blank=True, null=True, verbose_name='Active To'),
        ),
    ]
