# Generated by Django 2.1.7 on 2019-09-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_auto_20190919_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='product',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
