# Generated by Django 2.1.7 on 2019-09-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0007_auto_20190919_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='is_deposit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='is_range',
            field=models.BooleanField(default=False),
        ),
    ]
