# Generated by Django 2.1.7 on 2019-10-28 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20190919_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='is_affiliate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usergroup',
            name='is_player',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='groupType',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Permission'), (2, 'Static'), (3, 'Dynamic'), (1, 'other')], null=True, verbose_name='Group Type'),
        ),
    ]
