# Generated by Django 2.1.7 on 2019-10-31 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_auto_20191028_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergroup',
            old_name='is_affiliate',
            new_name='is_static',
        ),
        migrations.AlterField(
            model_name='usergroup',
            name='groupType',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Permission'), (2, 'Static'), (1, 'other')], null=True, verbose_name='Group Type'),
        ),
    ]
