# Generated by Django 2.1.7 on 2019-11-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20191031_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='groupType',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Permission'), (2, 'Static'), (4, 'Manager'), (1, 'other')], null=True, verbose_name='Group Type'),
        ),
    ]
