# Generated by Django 2.1.7 on 2019-06-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0004_auto_20190611_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='publish_time',
        ),
    ]
