# Generated by Django 2.1.7 on 2019-06-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0005_remove_notification_publish_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': 'Notification'},
        ),
        migrations.AlterField(
            model_name='notification',
            name='content',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('U', 'Unicast'), ('M', 'Multicast'), ('B', 'Broadcast')], max_length=1),
        ),
    ]
