# Generated by Django 2.1.7 on 2019-06-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0010_auto_20190618_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='create_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='publish_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Publish Time'),
        ),
    ]
