# Generated by Django 2.1.7 on 2019-06-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0012_auto_20190621_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationlog',
            name='act_on',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Action Time'),
        ),
    ]
