# Generated by Django 2.1.7 on 2019-06-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0013_auto_20190626_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='InLineImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='content',
        ),
        migrations.AddField(
            model_name='notification',
            name='content_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='notification',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_choice',
            field=models.CharField(choices=[('U', 'Unicast'), ('B', 'Broadcast')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.IntegerField(choices=[(1, 'ALERT'), (2, 'DIRECT')], default=1),
        ),
    ]
