# Generated by Django 2.1.7 on 2019-06-28 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0015_auto_20190627_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=256)),
                ('topic_arn', models.CharField(max_length=500)),
                ('subscribers', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
