# Generated by Django 2.1.7 on 2019-07-01 23:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0016_awstopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awstopic',
            name='subscribers',
        ),
        migrations.AddField(
            model_name='awstopic',
            name='create_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='awstopic',
            name='valid_until',
            field=models.DateField(blank=True, null=True, verbose_name='Valid Until'),
        ),
    ]
