# Generated by Django 2.1.7 on 2019-07-02 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0017_auto_20190701_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToAWSTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aws_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.AWSTopic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
