# Generated by Django 2.1.7 on 2019-07-02 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0018_usertoawstopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.AWSTopic'),
        ),
    ]
