# Generated by Django 2.1.7 on 2019-07-02 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0019_notification_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_choice',
            field=models.CharField(choices=[('U', 'Unicast'), ('M', 'Multicast'), ('B', 'Broadcast')], default='U', max_length=1),
        ),
    ]
