# Generated by Django 2.1.7 on 2019-07-08 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0020_auto_20190702_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticemessage',
            old_name='end_time',
            new_name='audit_date',
        ),
        migrations.RenameField(
            model_name='noticemessage',
            old_name='start_time',
            new_name='create_date',
        ),
        migrations.RemoveField(
            model_name='noticemessage',
            name='message',
        ),
        migrations.RemoveField(
            model_name='noticemessage',
            name='message_fr',
        ),
        migrations.RemoveField(
            model_name='noticemessage',
            name='message_zh',
        ),
        migrations.AddField(
            model_name='noticemessage',
            name='account_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticemessage',
            name='audit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticemessage',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticemessage',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='noticemessage',
            name='title',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
