# Generated by Django 2.1.7 on 2019-07-08 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0021_auto_20190708_1150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticemessage',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='noticemessage',
            name='audit',
        ),
        migrations.RemoveField(
            model_name='noticemessage',
            name='audit_date',
        ),
        migrations.RemoveField(
            model_name='noticemessage',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='noticemessage',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='noticemessage',
            name='status',
        ),
        migrations.RemoveField(
            model_name='noticemessage',
            name='title',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='create_on',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='act_on',
        ),
        migrations.RemoveField(
            model_name='notificationlog',
            name='actor_id',
        ),
        migrations.AddField(
            model_name='notification',
            name='account_type',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='audit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='audit_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Audit Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notifiers',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
