# Generated by Django 2.1.7 on 2019-07-08 23:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0022_auto_20190708_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='audit',
        ),
        migrations.AddField(
            model_name='notification',
            name='auditor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditor', to=settings.AUTH_USER_MODEL),
        ),
    ]
