# Generated by Django 2.1.7 on 2019-07-09 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0023_auto_20190708_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='account_type',
            field=models.CharField(default='Membership', max_length=200),
        ),
    ]
