# Generated by Django 2.1.7 on 2019-07-12 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0025_auto_20190712_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='audit_date',
            field=models.DateTimeField(null=True, verbose_name='Audit Date'),
        ),
    ]
