# Generated by Django 2.1.7 on 2019-07-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0026_auto_20190712_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_method',
            field=models.CharField(max_length=4),
        ),
    ]
