# Generated by Django 2.1.7 on 2019-07-25 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0029_auto_20190723_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_method',
            field=models.IntegerField(),
        ),
    ]
