# Generated by Django 2.1.7 on 2019-07-25 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0030_auto_20190725_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_method',
            field=models.CharField(max_length=4),
        ),
    ]
