# Generated by Django 2.1.7 on 2019-07-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0031_auto_20190725_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_choice',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_type',
        ),
        migrations.AddField(
            model_name='notification',
            name='campaign',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
