# Generated by Django 2.1.7 on 2019-07-30 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0001_initial'),
        ('operation', '0032_auto_20190729_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='bouns',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bonus.Bonus'),
        ),
    ]
