# Generated by Django 2.1.7 on 2019-08-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0033_notification_bouns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_method',
            field=models.CharField(default='D', max_length=4),
        ),
    ]
