# Generated by Django 2.1.7 on 2019-08-12 23:16

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0034_auto_20190801_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='content_text',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
