# Generated by Django 2.1.7 on 2019-08-13 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0036_auto_20190812_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='bouns',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bonus.Bonus'),
        ),
    ]
