# Generated by Django 2.1.7 on 2019-08-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0038_auto_20190813_1129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InLineImage',
        ),
        migrations.AddField(
            model_name='notification',
            name='status',
            field=models.IntegerField(choices=[(0, 'REJECTED'), (1, 'PENDING'), (2, 'APPROVED')], default=1),
        ),
    ]
