# Generated by Django 2.1.7 on 2019-08-14 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0040_notification_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
