# Generated by Django 2.1.7 on 2019-08-16 01:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0041_remove_notification_is_read'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NotificationUsers',
            new_name='NotificationToUsers',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='account_type',
        ),
    ]
