# Generated by Django 2.1.7 on 2019-08-19 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0042_auto_20190815_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtousers',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
