# Generated by Django 2.1.7 on 2019-08-22 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0043_notificationtousers_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_method',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notifiers',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='topic',
        ),
        migrations.AddField(
            model_name='notification',
            name='is_direct_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_email_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_push_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='is_sms_message',
            field=models.BooleanField(default=False),
        ),
    ]
