# Generated by Django 2.1.7 on 2019-08-23 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0044_auto_20190822_1200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='bouns',
            new_name='bonus',
        ),
    ]
