# Generated by Django 2.1.7 on 2019-09-05 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0045_auto_20190823_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtousers',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
