# Generated by Django 2.1.7 on 2019-09-18 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20190915_1733'),
        ('operation', '0047_auto_20190911_0958'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationToGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.UserGroup')),
            ],
        ),
        migrations.AlterField(
            model_name='notification',
            name='is_direct_message',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationtogroup',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operation.Notification'),
        ),
    ]
