# Generated by Django 2.1.7 on 2019-09-19 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_auto_20190915_1733'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('operation', '0048_auto_20190917_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('create_on', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='system.UserGroup')),
            ],
        ),
    ]
