# Generated by Django 2.1.7 on 2019-09-19 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0049_campaign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.Campaign'),
        ),
    ]
