# Generated by Django 2.1.1 on 2019-03-18 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_config_referral_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='referral_accept_points',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='referral_award_points',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='referral_limit',
        ),
    ]
