# Generated by Django 2.1.1 on 2019-03-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_auto_20190319_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='referred_who',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
