# Generated by Django 2.1.1 on 2019-03-28 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_auto_20190327_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='activation',
            new_name='activation',
        ),
    ]
