# Generated by Django 2.1.7 on 2019-04-04 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_auto_20190404_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='currency',
            field=models.CharField(choices=[('usd', 'USD'), ('eur', 'EUR'), ('jpy', 'JPY'), ('cny', 'CNY'), ('hkd', 'HKD'), ('aud', 'AUD')], default='usd', max_length=30),
        ),
    ]
