# Generated by Django 2.1.7 on 2019-04-15 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0068_usertag'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='userTag',
            field=models.ManyToManyField(to='users.UserTag'),
        ),
    ]
