# Generated by Django 2.1.7 on 2019-04-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0071_auto_20190405_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_option',
            field=models.CharField(blank=True, choices=[('Email', 'Email'), ('SMS', 'SMS'), ('OMS', 'OMS'), ('Push_Notification', 'Push Notification')], max_length=6, null=True),
        ),
    ]
