# Generated by Django 2.1.7 on 2019-04-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0072_auto_20190416_1103'),
        ('users', '0068_auto_20190408_1117'),
    ]

    operations = [
    ]
