# Generated by Django 2.1.7 on 2019-04-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0075_merge_20190418_1209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Customer User'},
        ),
        migrations.AlterModelOptions(
            name='usertag',
            options={'verbose_name_plural': 'User Tag'},
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
