# Generated by Django 2.1.7 on 2019-04-25 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0077_auto_20190421_2117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userwithtag',
            options={'verbose_name_plural': 'Assign tag to user'},
        ),
        migrations.AlterField(
            model_name='usertag',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Tag name'),
        ),
        migrations.AlterField(
            model_name='usertag',
            name='notes',
            field=models.CharField(max_length=200, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='userwithtag',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'pending'), (1, 'approved')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='userwithtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserTag', verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='userwithtag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='userwithtag',
            unique_together={('user', 'tag')},
        ),
    ]
