# Generated by Django 2.1.7 on 2019-04-26 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0078_auto_20190424_2146'),
        ('users', '0077_auto_20190425_1451'),
    ]

    operations = [
    ]
