# Generated by Django 2.1.7 on 2019-05-02 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0079_merge_20190426_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_addr', models.GenericIPAddressField(blank=True, null=True, verbose_name='action ip')),
                ('event_type', models.SmallIntegerField(choices=[(0, 'Login'), (1, 'Logout'), (2, 'Register'), (3, 'Deposit'), (4, 'Withdraw'), (5, 'Page Visit')], verbose_name='Event type')),
                ('device', models.CharField(blank=True, max_length=50, null=True)),
                ('browser', models.CharField(blank=True, max_length=50, null=True)),
                ('refer_url', models.CharField(blank=True, max_length=50, null=True)),
                ('dollow_amount', models.FloatField()),
                ('page_id', models.IntegerField(blank=True, null=True)),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created time')),
                ('modified_time', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='modified time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AlterModelOptions(
            name='userwithtag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Assign tag to user'},
        ),
    ]
