# Generated by Django 2.1.7 on 2019-05-02 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0080_auto_20190430_1152'),
        ('users', '0080_auto_20190429_0941'),
        ('users', '0080_auto_20190502_1223'),
    ]

    operations = [
    ]
