# Generated by Django 2.1.7 on 2019-05-09 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_auto_20190502_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='login_times',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='event_type',
            field=models.SmallIntegerField(choices=[(0, 'Login'), (1, 'Logout'), (2, 'Register'), (3, 'Deposit'), (4, 'Withdraw'), (5, 'Page Visit'), (6, 'bet')], verbose_name='Event type'),
        ),
    ]
