# Generated by Django 2.1.7 on 2019-05-10 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_merge_20190508_1138'),
        ('users', '0082_merge_20190507_1518'),
    ]

    operations = [
    ]
