# Generated by Django 2.1.7 on 2019-05-09 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_merge_20190507_1518'),
        ('users', '0083_auto_20190509_1203'),
    ]

    operations = [
    ]
