# Generated by Django 2.1.7 on 2019-05-14 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0083_auto_20190509_1203'),
        ('users', '0083_merge_20190510_1142'),
        ('users', '0082_merge_20190506_1545'),
    ]

    operations = [
    ]
