# Generated by Django 2.1.7 on 2019-05-13 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_merge_20190508_1138'),
        ('users', '0082_merge_20190506_1545'),
        ('users', '0083_bonus_bonusrequirement_userbonus'),
    ]

    operations = [
    ]
