# Generated by Django 2.1.7 on 2019-05-14 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_merge_20190513_1628'),
    ]

    operations = [
    ]
