# Generated by Django 2.1.7 on 2019-05-09 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_merge_20190509_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('bonus_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('expiration_days', models.IntegerField()),
                ('is_valid', models.BooleanField(default=False)),
                ('countries', models.CharField(max_length=500)),
                ('categories', models.CharField(max_length=500)),
                ('requirement_ids', models.CharField(max_length=500)),
                ('amount', models.FloatField()),
                ('percentage', models.FloatField()),
                ('is_free_bid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BonusRequirement',
            fields=[
                ('requirement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=50)),
                ('aggregate_method', models.CharField(max_length=50)),
                ('time_limit', models.IntegerField()),
                ('turnover_multiplier', models.IntegerField()),
                ('categories', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('is_successful', models.BooleanField(default=False)),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Bonus', verbose_name='Bonus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.RenameField(
            model_name='useraction',
            old_name='dollow_amount',
            new_name='dollar_amount',
        ),
    ]
