# Generated by Django 2.1.7 on 2019-05-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0085_auto_20190509_1218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraction',
            name='modified_time',
        ),
        migrations.AlterField(
            model_name='useraction',
            name='refer_url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
