# Generated by Django 2.1.7 on 2019-05-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_auto_20190512_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='dollar_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
