# Generated by Django 2.1.7 on 2019-05-16 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_merge_20190514_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_password_code',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
