# Generated by Django 2.1.7 on 2019-05-16 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0086_auto_20190515_2337'),
        ('users', '0087_customuser_reset_password_code'),
    ]

    operations = [
    ]
