# Generated by Django 2.1.7 on 2019-05-14 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0082_merge_20190506_1545'),
        ('users', '0087_auto_20190513_1635'),
        ('users', '0082_merge_20190508_1138'),
    ]

    operations = [
    ]
