# Generated by Django 2.1.7 on 2019-05-22 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0088_merge_20190516_1127'),
        ('users', '0088_merge_20190516_1512'),
    ]

    operations = [
    ]
