# Generated by Django 2.1.7 on 2019-05-22 22:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0089_merge_20190522_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='balance',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_betting_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='Last Betting Time'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='Last Login Time'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='member_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Blocked')], null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='modified_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Modified Time'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='time_of_registration',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Time of Registration'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_attribute',
            field=models.SmallIntegerField(choices=[(0, 'Direct User'), (1, 'User from Promo'), (2, 'Advertisements')], default=0, verbose_name='User Attribute'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verfication_time',
            field=models.DateTimeField(default=None, null=True, verbose_name='Time of Verification'),
        ),
    ]
