# Generated by Django 2.1.7 on 2019-05-29 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0091_auto_20190528_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id_image',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
