# Generated by Django 2.1.7 on 2019-05-31 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0093_auto_20190531_0040'),
        ('users', '0091_auto_20190524_1631'),
    ]

    operations = [
    ]
