# Generated by Django 2.1.7 on 2019-06-17 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0097_useractivity'),
        ('users', '0099_merge_20190614_1505'),
    ]

    operations = [
    ]
