# Generated by Django 2.1.7 on 2019-06-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0099_merge_20190614_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='active_downline_needed',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='customuser',
            name='affiliate_level',
            field=models.CharField(choices=[('Normal', 'Normal'), ('VIP', 'VIP')], default='Normal', max_length=50, verbose_name='Affiliate_level'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='affiliate_status',
            field=models.CharField(choices=[('Enabled', 'Enabled'), ('Disabled', 'Disabled')], default='Enabled', max_length=50, verbose_name='Affiliate_status'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='commission_level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customuser',
            name='commission_set',
            field=models.CharField(choices=[('System', 'System'), ('Personal', 'Personal')], default='System', max_length=50, verbose_name='Commission_set'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='downline_commision_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Downline Commision Percentage'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='monthly_downline_ftd_needed',
            field=models.IntegerField(default=6),
        ),
        migrations.AddField(
            model_name='customuser',
            name='transerfer_between_levels',
            field=models.BooleanField(default=False),
        ),
    ]
