# Generated by Django 2.1.7 on 2019-06-18 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0103_auto_20190617_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='commission_id',
        ),
        migrations.AddField(
            model_name='commission',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='commission_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Commission', verbose_name='Commission'),
        ),
    ]
