# Generated by Django 2.1.7 on 2019-07-15 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0109_auto_20190712_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'USD'), ('EUR', 'EUR'), ('JPY', 'JPY'), ('CNY', 'CNY'), ('HKD', 'HKD'), ('AUD', 'AUD'), ('THB', 'THB'), ('MYR', 'MYR'), ('VND', 'VND'), ('MMK', 'MMK'), ('XBT', 'XBT')], default='USD', max_length=30),
        ),
    ]
