# Generated by Django 2.1.7 on 2019-07-12 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0111_auto_20190710_1008'),
        ('users', '0109_auto_20190712_1003'),
    ]

    operations = [
    ]
