# Generated by Django 2.1.1 on 2019-02-02 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_game_catrgory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='catrgory',
            new_name='category',
        ),
    ]
