# Generated by Django 2.1.1 on 2019-02-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190218_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='zipcode',
        ),
    ]
