# Generated by Django 2.1.7 on 2019-03-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20190305_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='street_address_2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
