# Generated by Django 2.1.1 on 2019-03-14 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20190313_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referred_by',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
