# Generated by Django 2.1.1 on 2019-03-18 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='name',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
