# Generated by Django 2.1.1 on 2019-03-20 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_auto_20190319_1938'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='hop',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='hop',
            name='referred',
        ),
        migrations.RemoveField(
            model_name='hop',
            name='referrer',
        ),
        migrations.DeleteModel(
            name='Hop',
        ),
    ]
