# Generated by Django 2.1.1 on 2019-03-20 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_auto_20190319_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='referred_who',
        ),
    ]
