# Generated by Django 2.1.7 on 2019-03-22 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_noticemessage'),
        ('users', '0050_config_level'),
    ]

    operations = [
    ]
