# Generated by Django 2.1.1 on 2019-03-22 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_config_referee_add_balance_reward'),
        ('users', '0054_auto_20190322_0123'),
    ]

    operations = [
    ]
