# Generated by Django 2.1.7 on 2019-03-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_auto_20190324_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='name',
            field=models.CharField(choices=[('en', 'English'), ('zh', 'Chinese'), ('fr', 'Franch')], max_length=200),
        ),
    ]
