# Generated by Django 2.1.1 on 2019-03-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_auto_20190327_2320'),
        ('users', '0062_auto_20190328_0035'),
    ]

    operations = [
    ]
