# Generated by Django 2.1.7 on 2019-04-02 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_auto_20190326_1724'),
        ('users', '0064_auto_20190329_1516'),
    ]

    operations = [
    ]
