# Generated by Django 2.1.7 on 2019-04-02 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0065_merge_20190401_2211'),
        ('users', '0065_auto_20190329_1604'),
    ]

    operations = [
    ]
