# Generated by Django 2.1.7 on 2019-04-11 23:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0067_auto_20190410_1756'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('tag_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('name_zh', models.CharField(blank=True, max_length=50, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.CharField(max_length=200)),
            ],
        ),
    ]
