# Generated by Django 2.1.7 on 2019-04-18 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0073_merge_20190416_1139'),
        ('users', '0074_merge_20190417_2105'),
    ]

    operations = [
    ]
