# Generated by Django 2.1.7 on 2019-04-22 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0076_auto_20190418_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWithTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField()),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.UserTag')),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_tag',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_tag',
            field=models.ManyToManyField(blank=True, through='users.UserWithTag', to='users.UserTag'),
        ),
        migrations.AddField(
            model_name='userwithtag',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
