# Generated by Django 2.1.7 on 2019-05-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20190514_1301'),
        ('users', '0083_customuser_user_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_channel',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_deposit_channel',
            field=models.ManyToManyField(blank=True, through='accounting.DepositAccessManagement', to='accounting.DepositChannel', verbose_name='Deposit Channel'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_withdraw_channel',
            field=models.ManyToManyField(blank=True, through='accounting.WithdrawAccessManagement', to='accounting.WithdrawChannel', verbose_name='Withdraw Channel'),
        ),
    ]
