# Generated by Django 2.1.7 on 2019-05-14 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0084_merge_20190514_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('bonus_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('expiration_days', models.IntegerField()),
                ('is_valid', models.BooleanField(default=False)),
                ('countries', models.CharField(max_length=500)),
                ('categories', models.CharField(max_length=500)),
                ('requirement_ids', models.CharField(max_length=500)),
                ('amount', models.FloatField()),
                ('percentage', models.FloatField()),
                ('is_free_bid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BonusRequirement',
            fields=[
                ('requirement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.CharField(max_length=50)),
                ('aggregate_method', models.CharField(max_length=50)),
                ('time_limit', models.IntegerField()),
                ('turnover_multiplier', models.IntegerField()),
                ('categories', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='UserBonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('is_successful', models.BooleanField(default=False)),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Bonus', verbose_name='Bonus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.AlterModelOptions(
            name='useraction',
            options={'verbose_name_plural': 'User action history'},
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='dollow_amount',
        ),
        migrations.RemoveField(
            model_name='useraction',
            name='modified_time',
        ),
        migrations.AddField(
            model_name='useraction',
            name='dollar_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='browser',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Browser'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='device',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='event_type',
            field=models.SmallIntegerField(choices=[(0, 'Login'), (1, 'Logout'), (2, 'Register'), (3, 'Deposit'), (4, 'Withdraw'), (5, 'Page Visit'), (6, 'bet')], verbose_name='Event Type'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='ip_addr',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Action Ip'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='page_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Page'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='refer_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Refer URL'),
        ),
    ]
