# Generated by Django 2.1.7 on 2019-05-14 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0085_auto_20190514_1531'),
        ('users', '0084_auto_20190514_1301'),
    ]

    operations = [
    ]
