# Generated by Django 2.1.7 on 2019-05-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0085_merge_20190514_1519'),
        ('users', '0087_customuser_reset_password_code'),
    ]

    operations = [
    ]
