# Generated by Django 2.1.7 on 2019-05-28 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0090_auto_20190522_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraction',
            name='dollar_amount',
        ),
        migrations.AddField(
            model_name='customuser',
            name='id_image',
            field=models.ImageField(blank=True, upload_to='user_id_image'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='event_type',
            field=models.SmallIntegerField(choices=[(0, 'Login'), (1, 'Logout'), (2, 'Register'), (3, 'Page Visit')], verbose_name='Event Type'),
        ),
    ]
