# Generated by Django 2.1.7 on 2019-06-10 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0095_auto_20190603_1155'),
        ('users', '0091_auto_20190604_1429'),
    ]

    operations = [
    ]
