# Generated by Django 2.1.7 on 2019-06-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0095_auto_20190603_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ftd_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time of FTD'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_betting_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Betting Time'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_login_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Login Time'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='verfication_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Time of Verification'),
        ),
    ]
