# Generated by Django 2.1.7 on 2019-06-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0097_auto_20190610_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='agent_status',
            field=models.CharField(choices=[('Normal', 'Normal'), ('Block', 'Block')], default='Normal', max_length=50, verbose_name='Agent Status'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='agent_level',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Invalid', 'Invalid'), ('Normal', 'Normal'), ('Negative', 'Negative')], default='Normal', max_length=50, verbose_name='Agent Level'),
        ),
    ]
