# Generated by Django 2.1.7 on 2019-06-14 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0097_auto_20190614_1202'),
        ('users', '0098_auto_20190611_0006'),
    ]

    operations = [
    ]
