# Generated by Django 2.1.7 on 2019-06-24 04:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0100_merge_20190616_2225'),
    ]

    operations = [
        migrations.CreateModel(
            name='LimitationTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit_type', models.SmallIntegerField(choices=[(0, 'Bet'), (1, 'Loss'), (2, 'Deposit'), (3, 'Withdraw'), (4, 'Access Deny')], default=0)),
                ('amount', models.FloatField()),
                ('product', models.SmallIntegerField(choices=[(0, 'GB SPORTS'), (1, 'EZ SPORTS'), (2, 'GAMES'), (3, 'LOTTO'), (4, 'LIVE CASINO')], default=0)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('modified_time', models.DateTimeField(auto_now_add=True, verbose_name='Modified Time')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='block_timespan',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='temporary_block_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='limitationtable',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
