# Generated by Django 2.1.7 on 2019-06-21 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0100_merge_20190616_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='street_address_1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='street_address_2',
        ),
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('English', 'Englisg'), ('Chinese', 'Chinese'), ('French', 'French')], default='English', max_length=20),
        ),
    ]
