# Generated by Django 2.1.7 on 2019-06-25 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0102_auto_20190624_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='product',
            field=models.SmallIntegerField(choices=[(0, 'GB SPORTS'), (1, 'EZ SPORTS'), (2, 'GAMES'), (3, 'LOTTO'), (4, 'LIVE CASINO')], default=0, null=True),
        ),
    ]
