# Generated by Django 2.1.7 on 2019-06-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0102_auto_20190620_2247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='language',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='street_address',
        ),
        migrations.AddField(
            model_name='customuser',
            name='street_address_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='street_address_2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
