# Generated by Django 2.1.7 on 2019-06-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0103_auto_20190620_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Chinese', 'Chinese'), ('French', 'French')], default='English', max_length=20),
        ),
    ]
