# Generated by Django 2.1.7 on 2019-07-12 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0108_merge_20190626_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetKenoBalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BallID', models.CharField(max_length=30)),
                ('BallNum', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='BetKenoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DetailID', models.CharField(max_length=30)),
                ('SrcCode', models.CharField(max_length=30)),
                ('DrawNo', models.CharField(max_length=30)),
                ('OptCode', models.CharField(max_length=30)),
                ('OptParam1', models.CharField(max_length=30)),
                ('MaxRate', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GBSportWalletBet',
            fields=[
                ('Method', models.CharField(max_length=30)),
                ('Success', models.CharField(choices=[('1', '1'), ('0', '0')], max_length=1)),
                ('TransType', models.CharField(choices=[('Bet', 'Bet'), ('Discard', 'Discard'), ('Settle', 'Settle'), ('Balance', 'Balance')], max_length=20)),
                ('BetTotalCnt', models.CharField(max_length=30)),
                ('BetTotalAmt', models.CharField(max_length=30)),
                ('BetID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('BetGrpNO', models.CharField(max_length=50)),
                ('TPCode', models.CharField(max_length=30)),
                ('GBSN', models.CharField(max_length=30)),
                ('MemberID', models.CharField(max_length=30)),
                ('CurCode', models.CharField(max_length=30)),
                ('BetDT', models.CharField(max_length=100)),
                ('BetType', models.CharField(max_length=20)),
                ('BetTypeParam1', models.CharField(max_length=20)),
                ('BetTypeParam2', models.CharField(max_length=20)),
                ('Wintype', models.CharField(max_length=20)),
                ('HxMGUID', models.CharField(max_length=20)),
                ('InitBetAmt', models.CharField(max_length=30)),
                ('RealBetAmt', models.CharField(max_length=30)),
                ('HoldingAmt', models.CharField(max_length=30)),
                ('InitBetRate', models.CharField(max_length=30)),
                ('RealBetRate', models.CharField(max_length=20)),
                ('PreWinAmt', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='GBSportWalletSettle',
            fields=[
                ('Method', models.CharField(max_length=30)),
                ('Success', models.CharField(choices=[('1', '1'), ('0', '0')], max_length=1)),
                ('TransType', models.CharField(choices=[('Bet', 'Bet'), ('Discard', 'Discard'), ('Settle', 'Settle'), ('Balance', 'Balance')], max_length=20)),
                ('BetTotalCnt', models.CharField(max_length=30)),
                ('BetTotalAmt', models.CharField(max_length=30)),
                ('SettleID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('BetID', models.CharField(max_length=20)),
                ('BetGrpNO', models.CharField(max_length=50)),
                ('TPCode', models.CharField(max_length=30)),
                ('GBSN', models.CharField(max_length=30)),
                ('MemberID', models.CharField(max_length=30)),
                ('CurCode', models.CharField(max_length=30)),
                ('BetDT', models.CharField(max_length=100)),
                ('BetType', models.CharField(max_length=20)),
                ('BetTypeParam1', models.CharField(max_length=20)),
                ('BetTypeParam2', models.CharField(max_length=20)),
                ('Wintype', models.CharField(max_length=20)),
                ('HxMGUID', models.CharField(max_length=20)),
                ('InitBetAmt', models.CharField(max_length=30)),
                ('RealBetAmt', models.CharField(max_length=30)),
                ('HoldingAmt', models.CharField(max_length=30)),
                ('InitBetRate', models.CharField(max_length=30)),
                ('RealBetRate', models.CharField(max_length=20)),
                ('PreWinAmt', models.CharField(max_length=30)),
                ('BetResult', models.CharField(max_length=30)),
                ('WLAmt', models.CharField(max_length=30)),
                ('RefundBetAmt', models.CharField(max_length=30)),
                ('TicketBetAmt', models.CharField(max_length=30)),
                ('TicketResult', models.CharField(max_length=30)),
                ('TicketWLAmt', models.CharField(max_length=30)),
                ('SettleDT', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SettleKenoBalls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SettleODID', models.CharField(max_length=30)),
                ('BallID', models.CharField(max_length=30)),
                ('BallNum', models.CharField(max_length=30)),
                ('OptResult', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SettleKenoList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DetailID', models.CharField(max_length=30)),
                ('SrcCode', models.CharField(max_length=30)),
                ('DrawNo', models.CharField(max_length=30)),
                ('OptCode', models.CharField(max_length=30)),
                ('OptParam1', models.CharField(max_length=30)),
                ('MaxRate', models.CharField(max_length=30)),
                ('RealRate', models.CharField(max_length=30)),
                ('DrawDT', models.CharField(max_length=30)),
                ('OptResult', models.CharField(max_length=30)),
                ('SettleOID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.GBSportWalletSettle')),
            ],
        ),
        migrations.AddField(
            model_name='settlekenoballs',
            name='DetailID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SettleKenoList'),
        ),
        migrations.AddField(
            model_name='betkenolist',
            name='BetID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.GBSportWalletBet'),
        ),
        migrations.AddField(
            model_name='betkenoballs',
            name='DetailID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BetKenoList'),
        ),
    ]
