# Generated by Django 2.1.7 on 2019-07-10 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0109_limitation_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitation',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='limit_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='interval',
            field=models.SmallIntegerField(choices=[(0, 'per day'), (1, 'per week'), (2, 'per month'), (3, 'per six months'), (4, 'per one year'), (5, 'per three years'), (6, 'per five years')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='limit_type',
            field=models.SmallIntegerField(choices=[(0, 'Bet'), (1, 'Loss'), (2, 'Deposit'), (3, 'Withdraw'), (4, 'Access Deny'), (5, 'Block'), (6, 'Unblock')], default=0),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_user', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
