# Generated by Django 2.1.7 on 2019-07-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0110_auto_20190710_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
