# Generated by Django 2.1.7 on 2019-07-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0113_auto_20190716_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='AGGamemodels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionToken', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=100)),
                ('value', models.CharField(blank=True, max_length=100)),
                ('playname', models.CharField(blank=True, max_length=100)),
                ('agentCode', models.CharField(blank=True, max_length=100)),
                ('betTime', models.CharField(blank=True, max_length=100)),
                ('transactionID', models.CharField(blank=True, max_length=100)),
                ('platformType', models.CharField(blank=True, max_length=100)),
                ('Round', models.CharField(blank=True, max_length=100)),
                ('gametype', models.CharField(blank=True, max_length=100)),
                ('gameCode', models.CharField(blank=True, max_length=100)),
                ('tableCode', models.CharField(blank=True, max_length=100)),
                ('transactionType', models.CharField(blank=True, max_length=100)),
                ('transactionCode', models.CharField(blank=True, max_length=100)),
                ('deviceType', models.CharField(blank=True, max_length=100)),
                ('playtype', models.CharField(blank=True, max_length=100)),
                ('netAmount', models.CharField(blank=True, max_length=100)),
                ('validBetAmount', models.CharField(blank=True, max_length=100)),
                ('settletime', models.CharField(blank=True, max_length=100)),
                ('billNo', models.CharField(blank=True, max_length=100)),
                ('ticketStatus', models.CharField(blank=True, max_length=100)),
                ('gameResult', models.CharField(blank=True, max_length=100)),
                ('finish', models.CharField(blank=True, max_length=100)),
                ('remark', models.CharField(blank=True, max_length=100)),
                ('amount', models.CharField(blank=True, max_length=100)),
                ('gameId', models.CharField(blank=True, max_length=100)),
                ('time', models.CharField(blank=True, max_length=100)),
                ('roundId', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
