# Generated by Django 2.1.7 on 2019-07-25 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0117_auto_20190718_0911'),
        ('users', '0113_auto_20190716_1500'),
    ]

    operations = [
    ]
