# Generated by Django 2.1.7 on 2019-08-07 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0118_merge_20190725_1640'),
        ('users', '0118_auto_20190806_1435'),
    ]

    operations = [
    ]
