# Generated by Django 2.1.7 on 2019-08-07 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0118_merge_20190725_1640'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BonusRequirement',
        ),
        migrations.RemoveField(
            model_name='userbonus',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='userbonus',
            name='user',
        ),
        migrations.DeleteModel(
            name='Bonus',
        ),
        migrations.DeleteModel(
            name='UserBonus',
        ),
    ]
