# Generated by Django 2.1.7 on 2019-08-16 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0120_game_game_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bonus_wallet',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Bonus Wallet'),
        ),
    ]
