# Generated by Django 2.1.7 on 2019-08-11 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0120_auto_20190806_1814'),
        ('users', '0119_auto_20190807_1510'),
    ]

    operations = [
    ]
