# Generated by Django 2.1.7 on 2019-08-19 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0121_merge_20190810_1927'),
        ('users', '0120_game_game_url'),
    ]

    operations = [
    ]
