# Generated by Django 2.1.7 on 2019-08-21 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0123_auto_20190819_2359'),
        ('users', '0121_customuser_bonus_wallet'),
    ]

    operations = [
    ]
