# Generated by Django 2.1.7 on 2019-08-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0124_merge_20190821_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bonus_wallet',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, null=True, verbose_name='Bonus Wallet'),
        ),
    ]
