# Generated by Django 2.1.7 on 2019-08-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0124_auto_20190822_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitation',
            name='temporary_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
    ]
