# Generated by Django 2.1.7 on 2019-08-23 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0125_limitation_temporary_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='contact_methods',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_media',
            field=models.BooleanField(default=False),
        ),
    ]
