# Generated by Django 2.1.7 on 2019-08-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0126_auto_20190823_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='bonusesProgram',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='vipProgram',
            field=models.BooleanField(default=False),
        ),
    ]
