# Generated by Django 2.1.7 on 2019-08-28 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0127_auto_20190823_1409'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GBSportWallet',
            new_name='GameRequestsModel',
        ),
    ]
