# Generated by Django 2.1.7 on 2019-09-11 20:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0127_auto_20190823_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='created_time',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Created Time'),
        ),
    ]
