# Generated by Django 2.1.7 on 2019-09-04 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0129_auto_20190828_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerequestsmodel',
            name='transactionType',
        ),
    ]
