# Generated by Django 2.1.7 on 2019-09-04 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0130_remove_gamerequestsmodel_transactiontype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamerequestsmodel',
            name='TransType',
            field=models.CharField(max_length=30),
        ),
    ]
