# Generated by Django 2.1.7 on 2019-09-04 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0132_remove_gamerequestsmodel_playname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamerequestsmodel',
            name='betTime',
        ),
    ]
