# Generated by Django 2.1.7 on 2019-09-10 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0135_remove_gamerequestsmodel_settletime'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='activityCheck',
            field=models.SmallIntegerField(choices=[(0, '5 minutes'), (1, '30 minutes'), (2, '60 minutes'), (3, '120 minutes')], default=2),
        ),
    ]
