# Generated by Django 2.1.7 on 2019-09-17 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0135_remove_gamerequestsmodel_settletime'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='bonus',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='bonusprize',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='campaignref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='cash',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='isJackpotWin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='jackpotcontribution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='lang',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='last',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='organization',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='prepaidcost',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='prepaidref',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='prepaidticketid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='prepaidvalue',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='roundCount',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='ruleType',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='singleWin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='subreference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='tickets',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='totalWin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='version',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
