# Generated by Django 2.1.7 on 2019-09-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0136_customuser_activitycheck'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='activityCheck',
            new_name='activity_check',
        ),
    ]
