# Generated by Django 2.1.7 on 2019-09-17 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0138_game_image_url'),
        ('users', '0125_auto_20190823_1527'),
    ]

    operations = [
    ]
