# Generated by Django 2.1.7 on 2019-09-19 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0136_auto_20190917_1144'),
        ('users', '0139_merge_20190916_1716'),
    ]

    operations = [
    ]
