# Generated by Django 2.1.7 on 2019-09-17 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0140_auto_20190917_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='commission_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Commission', verbose_name='Commission'),
        ),
    ]
