# Generated by Django 2.1.7 on 2019-09-27 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0140_merge_20190919_1500'),
        ('users', '0128_auto_20190911_1314'),
    ]

    operations = [
    ]
