# Generated by Django 2.1.7 on 2019-09-26 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0140_merge_20190919_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='hostid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gamerequestsmodel',
            name='txnid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
