# Generated by Django 2.1.7 on 2019-09-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0141_merge_20190926_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='member_status',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Active'), (1, 'Inactive'), (2, 'Blocked')], default=0, null=True),
        ),
    ]
