# Generated by Django 2.1.7 on 2019-09-18 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0141_customuser_commission_id 12-14-08-106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_to_agent',
            new_name='user_to_agent_time',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='agent_level',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='agent_status',
        ),
        migrations.AddField(
            model_name='customuser',
            name='affiliate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='affiliate_status',
            field=models.CharField(choices=[('Active', 'Active'), ('VIP', 'VIP'), ('Negative', 'Negative'), ('Deactivated', 'Deactivated')], default='Active', max_length=50, verbose_name='Affiliate_status'),
        ),
    ]
