# Generated by Django 2.1.7 on 2019-09-27 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0141_merge_20190926_1735'),
        ('users', '0142_auto_20190926_1752'),
    ]

    operations = [
    ]
