# Generated by Django 2.1.7 on 2019-09-19 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0143_auto_20190918_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='affiliate',
        ),
    ]
