# Generated by Django 2.1.7 on 2019-09-27 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0143_merge_20190926_1840'),
        ('users', '0142_gamerequestsmodel_txn_reverse_id'),
    ]

    operations = [
    ]
