# Generated by Django 2.1.7 on 2019-09-20 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0144_remove_customuser_affiliate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='user_to_agent_time',
            new_name='user_to_affiliate_time',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_application_info',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Application Introduction'),
        ),
    ]
