# Generated by Django 2.1.7 on 2019-09-20 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0145_auto_20190920_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.SmallIntegerField(choices=[(0, 'Operation'), (1, 'Remark'), (2, 'Chat'), (3, 'Note'), (4, 'Affiliate Application')], default=0),
        ),
    ]
