# Generated by Django 2.1.7 on 2019-09-23 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0140_merge_20190919_1500'),
        ('users', '0146_auto_20190920_1513'),
    ]

    operations = [
    ]
