# Generated by Django 2.1.7 on 2019-09-27 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0148_auto_20190926_1832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referlink',
            old_name='genarate_time',
            new_name='genarated_time',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='commission_id',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='referral_id',
        ),
        migrations.AddField(
            model_name='commission',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referlink',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
