# Generated by Django 2.1.7 on 2019-09-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0150_auto_20190927_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referlink',
            name='refer_link_name',
            field=models.CharField(default='default', max_length=50, unique=True),
        ),
    ]
