# Generated by Django 2.1.7 on 2019-09-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0153_remove_commission_commission_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='commission_setting',
            field=models.CharField(choices=[('System', 'System'), ('Personal', 'Personal')], default='System', max_length=50),
        ),
    ]
