# Generated by Django 2.1.7 on 2019-09-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0144_merge_20190927_1632'),
        ('users', '0154_customuser_commission_setting'),
    ]

    operations = [
    ]
