# Generated by Django 2.1.7 on 2019-10-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0155_merge_20190930_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referlink',
            name='refer_link_name',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
