# Generated by Django 2.1.7 on 2019-10-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0156_auto_20191001_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='commision_status',
            new_name='commission_status',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='commision_percentage',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='downline_commision_percentage',
        ),
        migrations.AddField(
            model_name='commission',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='commission Percentage'),
        ),
        migrations.AddField(
            model_name='commission',
            name='downline_commission_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Downline commission Percentage'),
        ),
    ]
