# Generated by Django 2.1.7 on 2019-10-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0157_auto_20191002_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
