# Generated by Django 2.1.7 on 2019-10-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0157_auto_20191002_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='brand',
            field=models.CharField(blank=True, choices=[('letou', 'Letou'), ('ibet', 'iBet')], max_length=50, null=True),
        ),
    ]
