# Generated by Django 2.1.7 on 2019-10-15 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0159_auto_20191010_1448'),
        ('users', '0158_customuser_brand'),
    ]

    operations = [
    ]
