# Generated by Django 2.1.7 on 2019-10-11 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0159_auto_20191010_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='referlink',
            name='refer_link_code',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
