# Generated by Django 2.1.7 on 2019-10-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0160_merge_20191014_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='event_type',
            field=models.SmallIntegerField(choices=[(0, 'Login'), (1, 'Logout'), (2, 'Register'), (3, 'Page Visit'), (7, 'SMS CODE')], verbose_name='Event Type'),
        ),
    ]
