# Generated by Django 2.1.7 on 2019-10-11 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0160_referlink_refer_link_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referlink',
            name='refer_link_url',
        ),
    ]
