# Generated by Django 2.1.7 on 2019-10-14 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0161_remove_referlink_refer_link_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkhistory',
            name='link',
        ),
        migrations.RemoveField(
            model_name='referlink',
            name='refer_link_id',
        ),
        migrations.AddField(
            model_name='referlink',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referlink',
            name='refer_link_code',
            field=models.UUIDField(unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referlink',
            name='refer_link_name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='LinkHistory',
        ),
    ]
