# Generated by Django 2.1.7 on 2019-10-14 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0162_auto_20191013_1817'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referlink',
            old_name='genarated_time',
            new_name='generated_time',
        ),
    ]
