# Generated by Django 2.1.7 on 2019-10-14 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0164_auto_20191013_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referlink',
            name='refer_link_code',
            field=models.CharField(max_length=100),
        ),
    ]
