# Generated by Django 2.1.7 on 2019-10-14 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0164_auto_20191013_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referlink',
            name='refer_link_code',
        ),
        migrations.AlterUniqueTogether(
            name='referlink',
            unique_together={('user_id', 'refer_link_name')},
        ),
    ]
