# Generated by Django 2.1.7 on 2019-10-16 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0160_merge_20191014_1734'),
        ('users', '0165_auto_20191014_1651'),
    ]

    operations = [
    ]
