# Generated by Django 2.1.7 on 2019-10-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0167_auto_20191016_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='event_type',
            field=models.SmallIntegerField(choices=[(0, 'Login'), (1, 'Logout'), (2, 'Register'), (3, 'Page Visit'), (7, 'SMS CODE')], verbose_name='Event Type'),
        ),
    ]
