# Generated by Django 2.1.7 on 2019-10-19 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0167_auto_20191016_0026'),
        ('users', '0161_auto_20191018_1448'),
    ]

    operations = [
    ]
