# Generated by Django 2.1.7 on 2019-10-18 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0167_auto_20191016_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='security_answer',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Security answer'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='security_question',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'How old are you?'), (1, 'How tall are you?'), (2, 'How fat are you?')], null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='withdraw_password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='withdraw password'),
        ),
        migrations.AlterField(
            model_name='useraction',
            name='event_type',
            field=models.SmallIntegerField(choices=[(0, 'Login'), (1, 'Logout'), (2, 'Register'), (3, 'Page Visit'), (7, 'SMS CODE')], verbose_name='Event Type'),
        ),
    ]
