# Generated by Django 2.1.7 on 2019-10-21 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0161_auto_20191021_1158'),
        ('users', '0168_merge_20191018_1715'),
    ]

    operations = [
    ]
