# Generated by Django 2.1.7 on 2019-10-18 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0168_auto_20191018_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_application_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Application Time'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_to_affiliate_time',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Time of Becoming Agent'),
        ),
    ]
