# Generated by Django 2.1.7 on 2019-10-19 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0168_merge_20191018_1715'),
        ('users', '0169_auto_20191018_0015'),
    ]

    operations = [
    ]
