# Generated by Django 2.1.7 on 2019-10-23 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0170_merge_20191018_1723'),
        ('users', '0169_merge_20191021_1536'),
    ]

    operations = [
    ]
