# Generated by Django 2.1.7 on 2019-10-28 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0170_auto_20191022_1404'),
        ('users', '0171_merge_20191023_1445'),
    ]

    operations = [
    ]
