# Generated by Django 2.1.7 on 2019-10-28 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0173_auto_20191028_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='vip_level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Segmentation'),
        ),
    ]
