# Generated by Django 2.1.7 on 2019-10-28 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0172_auto_20191024_1744'),
        ('users', '0174_auto_20191028_1525'),
    ]

    operations = [
    ]
