# Generated by Django 2.1.7 on 2019-10-30 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0178_auto_20191029_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='referral_path',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
