# Generated by Django 2.1.7 on 2019-10-31 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0178_auto_20191029_1138'),
        ('users', '0175_merge_20191028_1559'),
    ]

    operations = [
    ]
