# Generated by Django 2.1.7 on 2019-10-29 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0178_auto_20191029_1138'),
        ('users', '0172_auto_20191024_1809'),
    ]

    operations = [
    ]
