# Generated by Django 2.1.7 on 2019-10-30 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0179_merge_20191029_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referchannel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
