# Generated by Django 2.1.7 on 2019-10-31 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0179_merge_20191030_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ea_wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='EA Wallet'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='currency',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'CNY'), (1, 'USD'), (2, 'THB'), (3, 'IDR'), (4, 'HKD'), (5, 'AUD'), (6, 'MYR'), (7, 'VND'), (8, 'MMK'), (9, 'XBT'), (10, 'EUR'), (11, 'NOK'), (12, 'GBP'), (13, 'TTC')], default=0),
        ),
    ]
