# Generated by Django 2.1.7 on 2019-10-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0179_customuser_referral_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCommission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_level', models.IntegerField(unique=True)),
                ('commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('downline_commission_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('active_downline_needed', models.IntegerField(default=6)),
                ('monthly_downline_ftd_needed', models.IntegerField(default=6)),
                ('ngr', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
    ]
