# Generated by Django 2.1.7 on 2019-10-31 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0179_customuser_onebook_wallet'),
        ('users', '0179_merge_20191030_1751'),
    ]

    operations = [
    ]
