# Generated by Django 2.1.7 on 2019-11-04 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0180_auto_20191030_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentation',
            name='level',
            field=models.IntegerField(),
        ),
    ]
