# Generated by Django 2.1.7 on 2019-11-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0181_merge_20191031_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcommission',
            name='active_downline_needed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='systemcommission',
            name='monthly_downline_ftd_needed',
            field=models.IntegerField(default=0),
        ),
    ]
