# Generated by Django 2.1.7 on 2019-11-04 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0180_auto_20191030_2347'),
        ('users', '0181_auto_20191031_1754'),
    ]

    operations = [
    ]
