# Generated by Django 2.1.7 on 2019-11-04 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0182_merge_20191104_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='currency',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'CNY'), (1, 'USD'), (2, 'THB'), (3, 'IDR'), (4, 'HKD'), (5, 'AUD'), (6, 'MYR'), (7, 'VND'), (8, 'MMK'), (9, 'XBT'), (10, 'EUR'), (11, 'NOK'), (12, 'GBP'), (20, 'UUD'), (13, 'TTC')], default=0),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Chinese', 'Chinese'), ('Thai', 'Thai'), ('Vietnamese', 'Vietnamese')], default='English', max_length=20),
        ),
    ]
