# Generated by Django 2.1.7 on 2019-11-07 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0181_segmentation_level'),
        ('users', '0183_auto_20191104_1329'),
    ]

    operations = [
    ]
