# Generated by Django 2.1.7 on 2019-11-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0183_auto_20191104_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ky_wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, null=True, verbose_name='Kaiyuan Wallet'),
        ),
    ]
