# Generated by Django 2.1.7 on 2019-11-13 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0183_auto_20191104_1329'),
        ('users', '0182_auto_20191102_2032'),
    ]

    operations = [
    ]
