# Generated by Django 2.1.7 on 2019-11-14 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0187_auto_20191111_1809'),
        ('users', '0185_auto_20191107_1158'),
    ]

    operations = [
    ]
