# Generated by Django 2.1.7 on 2019-11-14 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0184_customuser_ky_wallet'),
        ('users', '0187_auto_20191111_1809'),
    ]

    operations = [
    ]
