# Generated by Django 2.1.7 on 2019-11-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0188_merge_20191113_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ky_wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Kaiyuan Wallet'),
        ),
    ]
