# Generated by Django 2.1.7 on 2019-11-19 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0188_merge_20191113_1808'),
        ('users', '0184_merge_20191113_1401'),
    ]

    operations = [
    ]
