# Generated by Django 2.1.7 on 2019-12-04 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0189_auto_20191204_1101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraction',
            name='real_ip',
        ),
    ]
