# Generated by Django 2.1.7 on 2019-11-15 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0189_auto_20191114_1142'),
        ('users', '0188_merge_20191113_1808'),
    ]

    operations = [
    ]
