# Generated by Django 2.1.7 on 2019-11-21 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0189_merge_20191118_1952'),
        ('users', '0189_merge_20191118_2220'),
    ]

    operations = [
    ]
