# Generated by Django 2.1.7 on 2019-11-22 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0190_merge_20191115_1519'),
        ('users', '0190_merge_20191121_1211'),
    ]

    operations = [
    ]
