# Generated by Django 2.1.7 on 2019-11-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0191_merge_20191121_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
