# Generated by Django 2.1.7 on 2019-12-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0192_auto_20191126_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ime_wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='IMES Wallet'),
        ),
    ]
