# Generated by Django 2.1.7 on 2019-12-11 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0194_auto_20191205_1651'),
        ('users', '0191_auto_20191204_1150'),
    ]

    operations = [
    ]
