# Generated by Django 2.1.7 on 2019-12-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0194_auto_20191205_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ag_wallet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='AG Wallet'),
        ),
    ]
