# Generated by Django 2.1.7 on 2019-12-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0195_merge_20191210_0938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='imes_wallet',
        ),
    ]
