# Generated by Django 2.1.7 on 2019-12-11 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0195_merge_20191210_1802'),
        ('users', '0168_auto_20191018_1709'),
    ]

    operations = [
    ]
