# Generated by Django 2.1.7 on 2019-12-13 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0196_remove_customuser_imes_wallet'),
        ('users', '0195_merge_20191210_1802'),
    ]

    operations = [
    ]
