# Generated by Django 2.1.7 on 2019-12-17 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0197_merge_20191212_1753'),
        ('users', '0195_customuser_ag_wallet'),
    ]

    operations = [
    ]
