# Generated by Django 2.1.7 on 2019-12-19 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0064_merge_20191211_1732'),
        ('users', '0197_merge_20191212_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBonusWallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_amount', models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Wallet')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='userbonuswallet',
            unique_together={('user', 'category')},
        ),
    ]
