# Generated by Django 2.1.7 on 2019-12-20 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0198_auto_20191219_1145'),
        ('users', '0198_merge_20191216_1828'),
    ]

    operations = [
    ]
