# Generated by Django 2.1.7 on 2019-12-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0198_commission_ngr'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemcommission',
            name='operation_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='systemcommission',
            name='payment_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
