# Generated by Django 2.1.7 on 2019-12-24 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0199_merge_20191220_1526'),
        ('users', '0199_auto_20191218_0255'),
    ]

    operations = [
    ]
