# Generated by Django 2.1.7 on 2019-12-27 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0076_auto_20191212_1402'),
        ('users', '0200_merge_20191224_1420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commission',
            new_name='PersonalCommissionLevel',
        ),
        migrations.RenameModel(
            old_name='SystemCommission',
            new_name='SystemCommissionLevel',
        ),
    ]
