# Generated by Django 2.1.15 on 2020-01-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0201_auto_20191227_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitation',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='limitation',
            name='temporary_amount',
            field=models.DecimalField(blank=True, decimal_places=4, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='segmentation',
            name='annual_threshold',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='segmentation',
            name='deposit_amount_daily',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='segmentation',
            name='deposit_amount_monthly',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='segmentation',
            name='platform_turnover_daily',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
        migrations.AlterField(
            model_name='segmentation',
            name='turnover_threshold',
            field=models.DecimalField(decimal_places=4, max_digits=20),
        ),
    ]
