# Generated by Django 2.1.15 on 2020-01-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0202_auto_20200108_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='ag_wallet',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='AG Wallet'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ea_wallet',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='EA Wallet'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ky_wallet',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Kaiyuan Wallet'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='other_game_wallet',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Other Game Wallet'),
        ),
        migrations.AlterField(
            model_name='personalcommissionlevel',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='commission Percentage'),
        ),
        migrations.AlterField(
            model_name='personalcommissionlevel',
            name='downline_commission_percentage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Downline commission Percentage'),
        ),
        migrations.AlterField(
            model_name='personalcommissionlevel',
            name='ngr',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='systemcommissionlevel',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='systemcommissionlevel',
            name='downline_commission_percentage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='systemcommissionlevel',
            name='ngr',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='systemcommissionlevel',
            name='operation_fee',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='systemcommissionlevel',
            name='payment_fee',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=5),
        ),
    ]
