# Generated by Django 2.1.7 on 2020-01-15 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0203_auto_20200108_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemcommissionlevel',
            name='commission_percentage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='systemcommissionlevel',
            name='downline_commission_percentage',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='systemcommissionlevel',
            name='operation_fee',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='systemcommissionlevel',
            name='payment_fee',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=7),
        ),
    ]
