# Generated by Django 2.1.7 on 2020-01-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0204_auto_20200114_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='gpi_wallet',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='GPI Wallet'),
        ),
    ]
