# Generated by Django 2.1.15 on 2020-01-31 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0207_customuser_ftd_time_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='member_changed_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Status Changed Time'),
        ),
    ]
