# Generated by Django 2.1.7 on 2020-02-04 00:04

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0207_withdrawaccounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='withdrawaccounts',
            name='account_no',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50)),
        ),
    ]
