# Generated by Django 2.1.15 on 2020-02-07 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0209_customuser_member_changed_by'),
        ('users', '0208_auto_20200203_1604'),
    ]

    operations = [
    ]
