# Generated by Django 2.1.15 on 2020-02-13 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0210_merge_20200206_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawaccounts',
            name='bank_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
