# Generated by Django 2.1.15 on 2020-02-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0210_merge_20200206_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='verfication_time',
            new_name='verification_time',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='risk_level',
            field=models.SmallIntegerField(choices=[(0, 'Very High'), (1, 'High'), (2, 'Medium'), (3, 'Low'), (4, 'Very Low'), (5, 'VIP'), (6, 'Business')], default=0),
        ),
    ]
