# Generated by Django 2.1.15 on 2020-02-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0211_auto_20200210_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivity',
            name='system_message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='message',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
