# Generated by Django 2.1.15 on 2020-02-12 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0212_auto_20200211_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.SmallIntegerField(choices=[(0, 'System'), (1, 'Remark'), (2, 'Message'), (3, 'Note'), (4, 'Upload ID image')], default=0),
        ),
    ]
