# Generated by Django 2.1.15 on 2020-02-14 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0211_withdrawaccounts_bank_code'),
        ('users', '0213_auto_20200212_1126'),
    ]

    operations = [
    ]
