# Generated by Django 2.1.15 on 2020-02-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0214_merge_20200214_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='activity_type',
            field=models.SmallIntegerField(choices=[(0, 'System'), (1, 'Remark'), (2, 'Message'), (3, 'Note'), (4, 'Upload ID image'), (5, 'Remove ID image'), (6, 'Close Account'), (7, 'Open Account')], default=0),
        ),
    ]
