# Generated by Django 2.1.7 on 2019-07-16 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20190418_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_id',
        ),
        migrations.AddField(
            model_name='game',
            name='attribute',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Time'),
        ),
        migrations.AddField(
            model_name='game',
            name='imageURL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='modifited_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Modifited Time'),
        ),
        migrations.AddField(
            model_name='game',
            name='popularity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='game',
            name='provider',
            field=models.SmallIntegerField(choices=[(0, 'SPORTS_1'), (1, 'SPORTS_2'), (2, 'CASINO_1'), (3, 'CASINO_2'), (4, 'SLOT_1'), (5, 'SLOT_2')], default=0),
        ),
    ]
