# Generated by Django 2.1.7 on 2019-07-16 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20190715_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='attribute',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
