# Generated by Django 2.1.7 on 2019-07-24 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20190723_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.Category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='notes',
            field=models.CharField(max_length=500),
        ),
    ]
