# Generated by Django 2.1.7 on 2019-10-14 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_eaticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(max_length=100)),
                ('type', models.SmallIntegerField(choices=[(0, 'Sports'), (1, 'Games'), (2, 'Live Casino'), (3, 'Financial'), (4, 'General')])),
                ('market', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GameProviderWithCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Category')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.GameProvider')),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.GameProvider'),
        ),
    ]
