# Generated by Django 2.1.7 on 2019-10-15 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0009_eaticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='FGGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=50, null=True)),
                ('party_id', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
