# Generated by Django 2.1.7 on 2019-10-17 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_gdcasino'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gdcasino',
            name='merchant_id',
        ),
        migrations.RemoveField(
            model_name='gdcasino',
            name='method',
        ),
    ]
