# Generated by Django 2.1.7 on 2019-10-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0010_auto_20191014_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='category',
            field=models.CharField(blank=True, default='Slots', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='modifited_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Modified Time'),
        ),
    ]
