# Generated by Django 2.1.7 on 2019-10-16 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20191016_1107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='modifited_time',
            new_name='modified_time',
        ),
    ]
