# Generated by Django 2.1.7 on 2019-10-18 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20191017_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='GDGetUserBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('StatusCode', models.SmallIntegerField(choices=[(0, 'SUCCESS'), (1, 'FAILED'), (2, 'CREATED'), (3, 'PENDING'), (4, 'APPROVED'), (5, 'CANCELED'), (6, 'COMPLETED'), (7, 'RESEND'), (8, 'REJECTED'), (9, 'HELD')], default=3)),
                ('UserBalance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='GDCasino',
        ),
    ]
