# Generated by Django 2.1.7 on 2019-10-18 22:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0011_auto_20191018_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='modifited_time',
        ),
        migrations.AddField(
            model_name='game',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified Time'),
        ),
        migrations.AddField(
            model_name='gamebet',
            name='other_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
