# Generated by Django 2.1.7 on 2019-10-18 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20191018_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamebet',
            name='outcome',
        ),
    ]
