# Generated by Django 2.1.7 on 2019-10-16 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20191016_1457'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fgsession',
            old_name='username',
            new_name='user_name',
        ),
    ]
