# Generated by Django 2.1.7 on 2019-10-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0012_auto_20191016_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='gameURL',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
