# Generated by Django 2.1.7 on 2019-10-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_auto_20191016_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fgsession',
            name='user_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
