# Generated by Django 2.1.7 on 2019-10-17 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0013_game_gameurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameBet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200)),
                ('amount_wagered', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_won', models.DecimalField(decimal_places=2, max_digits=12)),
                ('outcome', models.BooleanField()),
                ('odds', models.IntegerField()),
                ('bet_type', models.CharField(blank=True, choices=[('SPREAD', 'Spread'), ('LINE', 'Moneyline'), ('OU', 'Total O/U')], max_length=6, null=True)),
                ('line', models.CharField(blank=True, max_length=50, null=True)),
                ('currency', models.SmallIntegerField(choices=[(0, 'CNY'), (1, 'USD'), (2, 'THB'), (3, 'IDR'), (4, 'HKD'), (5, 'AUD'), (6, 'MYR'), (7, 'VND'), (8, 'MMK'), (9, 'XBT'), (10, 'EUR'), (11, 'NOK'), (12, 'GBP')], default=0, verbose_name='Currency')),
                ('market', models.SmallIntegerField(choices=[(0, 'ibet-VN'), (1, 'ibet-TH')])),
                ('ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('bet_time', models.DateTimeField(auto_now_add=True, verbose_name='Time Bet was Placed')),
                ('resolved_time', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Category')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.GameProvider')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='game',
            name='modified_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Modified Time'),
        ),
    ]
