# Generated by Django 2.1.7 on 2019-10-18 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0013_remove_gamebet_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamebet',
            name='outcome',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Win'), (1, 'Lose'), (2, 'Tie/Push'), (3, 'Void')], null=True),
        ),
    ]
