# Generated by Django 2.1.7 on 2019-10-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_gamebet_outcome'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GameAttribute',
        ),
        migrations.RemoveField(
            model_name='game',
            name='status_id',
        ),
        migrations.AlterField(
            model_name='gamebet',
            name='odds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
