# Generated by Django 2.1.7 on 2019-10-18 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0014_auto_20191018_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdgetuserbalance',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
