# Generated by Django 2.1.7 on 2019-10-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_auto_20191021_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebet',
            name='currency',
            field=models.CharField(max_length=3, verbose_name='Currency'),
        ),
    ]
