# Generated by Django 2.1.7 on 2019-10-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0015_auto_20191018_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdgetuserbalance',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gdgetuserbalance',
            name='gameId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='gdgetuserbalance',
            name='gameType',
            field=models.SmallIntegerField(choices=[(6, 'Baccarat'), (28, 'Roulette'), (29, 'Sic bo'), (100, 'Slot game')], default=6),
        ),
        migrations.AddField(
            model_name='gdgetuserbalance',
            name='transactionId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gdgetuserbalance',
            name='StatusCode',
            field=models.SmallIntegerField(choices=[(-1, 'UNKNOWN_ERROR'), (0, 'OK'), (1, 'INVAILD_PARAMETER'), (2, 'INVAILD_TOKEN_ID'), (3, 'BET_ALREDY_SETTLED'), (4, 'BET_DOES_NOT_EXIST'), (5, 'BET_ALREADY_EXIST'), (6, 'ACCOUNT_LOCKED'), (7, 'INSUFFUCIENT_FUNDS'), (8, 'RETRY_TRANSACTION'), (201, 'INSUFFUCIENT_FUNDS_1(for maxbet)'), (202, 'ACCOUNT_LOCKED_1(for maxbet)'), (206, 'ABOVE_PLAYER_LIMIT_1(for maxbet)')]),
        ),
    ]
