# Generated by Django 2.1.7 on 2019-10-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20191018_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdgetuserbalance',
            name='gameType',
            field=models.SmallIntegerField(choices=[(0, 'None'), (6, 'Baccarat'), (28, 'Roulette'), (29, 'Sic bo'), (100, 'Slot game')], default=6),
        ),
    ]
