# Generated by Django 2.1.7 on 2019-10-18 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20191016_1632'),
        ('games', '0010_auto_20191014_0949'),
    ]

    operations = [
    ]
