# Generated by Django 2.1.7 on 2019-10-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0016_auto_20191021_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebet',
            name='amount_won',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
