# Generated by Django 2.1.7 on 2019-10-18 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_merge_20191018_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='fgsession',
            name='uuid',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
