# Generated by Django 2.1.7 on 2019-10-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_auto_20191021_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gdgetuserbalance',
            name='StatusCode',
        ),
        migrations.RemoveField(
            model_name='gdgetuserbalance',
            name='UserBalance',
        ),
        migrations.AddField(
            model_name='gdgetuserbalance',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
