# Generated by Django 2.1.7 on 2019-10-21 21:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0018_auto_20191021_1421'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GDGetUserBalance',
            new_name='GDCasino',
        ),
    ]
