# Generated by Django 2.1.7 on 2019-10-21 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0017_auto_20191021_1158'),
        ('games', '0018_fgsession_uuid'),
    ]

    operations = [
    ]
