# Generated by Django 2.1.7 on 2019-10-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_auto_20191021_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdcasino',
            name='clientType',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='gdcasino',
            name='gameView',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='gdcasino',
            name='ipAddress',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='gdcasino',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='gdcasino',
            name='gameType',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'None'), (6, 'Baccarat'), (28, 'Roulette'), (29, 'Sic bo'), (100, 'Slot game')], default=6, null=True),
        ),
    ]
