# Generated by Django 2.1.7 on 2019-10-21 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0020_auto_20191021_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdcasino',
            name='tipId',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
