# Generated by Django 2.1.7 on 2019-10-21 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0021_gdcasino_tipid'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdcasino',
            name='cancelReason',
            field=models.SmallIntegerField(choices=[(0, 'Game round is cancelled.'), (1, 'Debit response timeout.'), (2, 'Abnormal bet is voided.'), (3, 'Betting time is ended'), (4, 'Debit reply is in wrong format.')], default=0),
        ),
    ]
