# Generated by Django 2.1.7 on 2019-10-21 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0022_gdcasino_cancelreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='gdcasino',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'PENDING'), (1, 'DEBIT'), (2, 'CREDIT'), (3, 'TIP'), (4, 'CANCEL')], default=0),
        ),
    ]
