# Generated by Django 2.1.7 on 2019-10-21 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0024_auto_20191021_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdcasino',
            name='cancelReason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
