# Generated by Django 2.1.7 on 2019-10-22 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0018_fgsession_uuid'),
        ('games', '0026_auto_20191021_1650'),
    ]

    operations = [
    ]
