# Generated by Django 2.1.7 on 2019-10-22 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0027_merge_20191021_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gdcasino',
            name='cancelReason',
            field=models.CharField(choices=[('NONE', 'None'), ('CANCELLED_ROUND', 'Game round is cancelled.'), ('DEBIT_TIME_OUT', 'Debit response timeout.'), ('VOIDED_BET', 'Abnormal bet is voided.'), ('BETTING_TIME_FINISHED', 'Betting time is ended'), ('INVALID_DEBIT_REPLY', 'Debit reply is in wrong format.')], default='NONE', max_length=20),
        ),
    ]
