# Generated by Django 2.1.7 on 2019-10-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0019_merge_20191021_1536'),
        ('games', '0028_auto_20191021_1741'),
    ]

    operations = [
    ]
