# Generated by Django 2.1.7 on 2019-10-23 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0029_merge_20191022_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gdcasino',
            name='username',
        ),
        migrations.DeleteModel(
            name='GDCasino',
        ),
    ]
