# Generated by Django 2.1.7 on 2019-10-25 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0030_auto_20191023_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebet',
            name='bet_type',
            field=models.CharField(blank=True, choices=[('SPREAD', 'Spread'), ('LINE', 'Moneyline'), ('OU', 'Total O/U'), ('TIP', 'Tip'), ('Single', 'Single'), ('Parlay', 'Parlay')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='gamebet',
            name='market',
            field=models.SmallIntegerField(choices=[(0, 'ibet-VN'), (1, 'ibet-TH'), (2, 'ibet-CN')]),
        ),
    ]
