# Generated by Django 2.1.7 on 2019-11-02 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_auto_20191025_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
