# Generated by Django 2.1.7 on 2019-10-31 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0031_auto_20191025_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebet',
            name='odds',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
