# Generated by Django 2.1.7 on 2019-11-04 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0034_auto_20191031_1754'),
        ('games', '0032_auto_20191101_1734'),
    ]

    operations = [
    ]
