# Generated by Django 2.1.7 on 2019-11-08 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0035_merge_20191104_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebet',
            name='amount_wagered',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
    ]
