# Generated by Django 2.1.7 on 2019-11-12 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0037_auto_20191111_1001'),
        ('games', '0039_remove_gamebet_transaction_id'),
    ]

    operations = [
    ]
