# Generated by Django 2.1.7 on 2019-11-18 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0040_merge_20191112_1312'),
        ('games', '0036_mgtoken'),
    ]

    operations = [
    ]
