# Generated by Django 2.1.7 on 2019-11-13 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0040_merge_20191112_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamebet',
            name='currency',
        ),
    ]
