# Generated by Django 2.1.7 on 2019-11-19 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0040_merge_20191112_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebet',
            name='bet_type',
            field=models.CharField(blank=True, choices=[('SPREAD', 'Spread'), ('LINE', 'Moneyline'), ('OU', 'Total O/U'), ('TIP', 'Tip'), ('Single', 'Single'), ('Parlay', 'Parlay'), ('Other', 'Other')], max_length=6, null=True),
        ),
    ]
