# Generated by Django 2.1.7 on 2019-11-19 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('games', '0040_merge_20191112_1312'),
    ]

    operations = [
        migrations.CreateModel(
            name='PNGTicket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('png_ticket', models.UUIDField()),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
