# Generated by Django 2.1.7 on 2019-11-19 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0041_auto_20191118_1602'),
        ('games', '0041_merge_20191118_1518'),
    ]

    operations = [
    ]
