# Generated by Django 2.1.7 on 2019-11-18 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0041_gamebet_created_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamebet',
            name='created_time',
        ),
    ]
