# Generated by Django 2.1.7 on 2019-11-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0042_merge_20191118_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebet',
            name='outcome',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Win'), (1, 'Lose'), (2, 'Tie/Push'), (3, 'Void'), (4, 'Running'), (5, 'Draw'), (6, 'Half lose'), (7, 'Rollback'), (8, 'Cancel'), (9, 'Cash')], null=True),
        ),
    ]
