# Generated by Django 2.1.7 on 2019-11-13 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0042_auto_20191112_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebet',
            name='transaction_id',
            field=models.CharField(max_length=200, verbose_name='Transaction id'),
        ),
    ]
