# Generated by Django 2.1.7 on 2019-11-20 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0041_qtsession'),
        ('games', '0043_auto_20191119_1048'),
    ]

    operations = [
    ]
