# Generated by Django 2.1.7 on 2019-11-14 01:51

from django.db import migrations, models
import games.models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0043_auto_20191112_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebet',
            name='transaction_id',
            field=models.CharField(default=games.models.random_string, max_length=200, unique=True, verbose_name='Transaction id'),
        ),
    ]
