# Generated by Django 2.1.7 on 2019-11-15 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0045_auto_20191114_2005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='gameURL',
            new_name='game_url',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='imageURL',
            new_name='image_url',
        ),
        migrations.AddField(
            model_name='game',
            name='game_guest_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
