# Generated by Django 2.1.7 on 2019-11-20 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0046_auto_20191114_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_guest_url',
        ),
    ]
