# Generated by Django 2.1.7 on 2019-11-20 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0047_remove_game_game_guest_url'),
        ('games', '0043_auto_20191119_1048'),
    ]

    operations = [
    ]
