# Generated by Django 2.1.7 on 2019-11-20 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0044_merge_20191120_1140'),
        ('games', '0048_merge_20191120_0406'),
    ]

    operations = [
    ]
