# Generated by Django 2.1.7 on 2019-11-21 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0042_remove_gamebet_created_time'),
        ('games', '0049_merge_20191120_1538'),
    ]

    operations = [
    ]
