# Generated by Django 2.1.7 on 2019-11-21 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0049_merge_20191120_1538'),
        ('games', '0043_auto_20191119_1522'),
    ]

    operations = [
    ]
