# Generated by Django 2.1.7 on 2019-11-21 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0050_merge_20191121_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebet',
            name='bet_type',
            field=models.CharField(blank=True, choices=[('SPREAD', 'Spread'), ('LINE', 'Moneyline'), ('OU', 'Total O/U'), ('TIP', 'Tip'), ('Single', 'Single'), ('Parlay', 'Parlay'), ('Other', 'Other')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='gamebet',
            name='outcome',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Win'), (1, 'Lose'), (2, 'Tie/Push'), (3, 'Void'), (4, 'Running'), (5, 'Draw'), (6, 'Half lose'), (7, 'Rollback'), (8, 'Cancel'), (9, 'Cash'), (9, 'Cash'), (10, 'Half won')], null=True),
        ),
    ]
