# Generated by Django 2.1.7 on 2019-11-21 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0051_auto_20191121_1449'),
        ('games', '0043_auto_20191118_1958'),
    ]

    operations = [
    ]
