# Generated by Django 2.1.7 on 2019-11-27 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0050_merge_20191121_1349'),
        ('games', '0054_auto_20191122_1548'),
    ]

    operations = [
    ]
