# Generated by Django 2.1.7 on 2019-11-25 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0041_pngticket'),
        ('games', '0054_auto_20191122_1548'),
    ]

    operations = [
    ]
