# Generated by Django 2.1.7 on 2019-11-28 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0050_merge_20191121_1349'),
        ('games', '0055_merge_20191125_1102'),
    ]

    operations = [
    ]
