# Generated by Django 2.1.7 on 2019-11-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0056_merge_20191127_1656'),
        ('games', '0056_merge_20191127_1643'),
    ]

    operations = [
    ]
