# Generated by Django 2.1.7 on 2019-12-05 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0057_auto_20191204_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
