# Generated by Django 2.1.7 on 2019-12-06 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0057_auto_20191205_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprovider',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Sports'), (1, 'Games'), (2, 'Live Casino'), (3, 'Table Games'), (4, 'General')]),
        ),
    ]
