# Generated by Django 2.1.7 on 2019-12-05 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0059_auto_20191205_1104'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_id',
            new_name='smallgame_id',
        ),
    ]
