# Generated by Django 2.1.7 on 2019-12-07 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0059_gameprovider_is_transfer_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprovider',
            name='is_transfer_wallet',
            field=models.BooleanField(default=False),
        ),
    ]
