# Generated by Django 2.1.7 on 2019-12-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0060_auto_20191205_1531'),
        ('games', '0060_auto_20191206_1728'),
    ]

    operations = [
    ]
