# Generated by Django 2.1.7 on 2019-12-10 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0061_merge_20191206_1752'),
        ('games', '0061_gamebet_user_name'),
    ]

    operations = [
    ]
