# Generated by Django 2.1.7 on 2019-12-12 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0057_auto_20191203_1453'),
        ('games', '0063_auto_20191209_1607'),
    ]

    operations = [
    ]
