# Generated by Django 2.1.15 on 2019-12-21 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0064_merge_20191211_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_order',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
