# Generated by Django 2.1.15 on 2020-01-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0065_category_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='popularity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='gamebet',
            name='amount_wagered',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='gamebet',
            name='amount_won',
            field=models.DecimalField(decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='gamebet',
            name='odds',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
