# Generated by Django 2.1.15 on 2020-01-06 18:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0065_category_category_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebet',
            name='bet_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time Bet was Placed'),
        ),
    ]
