# Generated by Django 2.1.15 on 2020-01-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0066_auto_20200108_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameprovider',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'Sports'), (1, 'Games'), (2, 'Live Casino'), (3, 'Table Games'), (4, 'General'), (5, 'Lottory')]),
        ),
    ]
