# Generated by Django 2.1.15 on 2020-01-06 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0066_auto_20200106_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameprovider',
            name='timezone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
