# Generated by Django 2.1.15 on 2020-01-07 00:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0067_gameprovider_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamebet',
            name='bet_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='Time Bet was Placed'),
        ),
    ]
