# Generated by Django 2.1.15 on 2020-01-10 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0066_auto_20200108_1537'),
        ('games', '0068_auto_20200106_1606'),
    ]

    operations = [
    ]
