# Generated by Django 2.1.15 on 2020-01-15 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0067_auto_20200113_2259'),
        ('games', '0069_merge_20200110_1555'),
    ]

    operations = [
    ]
