# Generated by Django 2.1.15 on 2020-01-18 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0069_gamebet_result'),
        ('games', '0070_merge_20200114_1716'),
    ]

    operations = [
    ]
