# Generated by Django 2.1.15 on 2020-02-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0072_auto_20200121_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='mobile_game_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
