# Generated by Django 2.1.15 on 2020-02-24 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0073_game_mobile_game_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMSTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.SmallIntegerField(choices=[(0, 'Home Banner'), (1, 'Live Casino Banner'), (2, 'Casino Banner'), (3, 'Bonus')])),
                ('position_code', models.CharField(max_length=30, null=True)),
                ('image_url', models.CharField(blank=True, max_length=200, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
