# Generated by Django 2.1.7 on 2019-05-14 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositAccessManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Deposit Access management',
                'verbose_name_plural': 'Deposit Access management',
            },
        ),
        migrations.CreateModel(
            name='DepositChannel',
            fields=[
                ('thridParty_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thridParty_name', models.SmallIntegerField(choices=[(0, 'Alipay'), (1, 'Wechat'), (2, 'Card'), (3, 'Qaicash'), (4, 'Asia Pay')], default=2, verbose_name='Name')),
                ('currency', models.SmallIntegerField(choices=[(0, 'CNY'), (1, 'USD'), (2, 'PHP')], default=0, verbose_name='Currency')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Min Amount')),
                ('max_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Max Amount')),
                ('switch', models.BooleanField(default=True, verbose_name='Active')),
                ('priority', models.IntegerField(default=0, verbose_name='Priority')),
                ('deposit_channel', models.ManyToManyField(blank=True, related_name='sb', through='accounting.DepositAccessManagement', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deposit Channel',
                'verbose_name_plural': 'Deposit Channel',
            },
        ),
        migrations.CreateModel(
            name='WithdrawChannel',
            fields=[
                ('thridParty_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thridParty_name', models.SmallIntegerField(choices=[(0, 'Alipay'), (1, 'Wechat'), (2, 'Card'), (3, 'Qaicash'), (4, 'Asia Pay')], default=2, verbose_name='Name')),
                ('currency', models.SmallIntegerField(choices=[(0, 'CNY'), (1, 'USD'), (2, 'PHP')], default=0, verbose_name='Currency')),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Min Amount')),
                ('max_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Max Amount')),
                ('switch', models.BooleanField(default=True, verbose_name='Active')),
                ('transaction_fee', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Transaction Fee')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Withdraw Channel',
                'verbose_name_plural': 'Withdraw Channel',
            },
        ),
        migrations.DeleteModel(
            name='ThirdParty',
        ),
        migrations.DeleteModel(
            name='Deposit',
        ),
        migrations.CreateModel(
            name='DepositReview',
            fields=[
            ],
            options={
                'verbose_name': 'Deposit Review',
                'verbose_name_plural': 'Deposit Review',
                'proxy': True,
                'indexes': [],
            },
            bases=('accounting.transaction',),
        ),
        migrations.CreateModel(
            name='WithdrawReview',
            fields=[
            ],
            options={
                'verbose_name': 'Withdraw Review',
                'verbose_name_plural': 'Withdraw Review',
                'proxy': True,
                'indexes': [],
            },
            bases=('accounting.transaction',),
        ),
        migrations.AddField(
            model_name='transaction',
            name='review_status',
            field=models.SmallIntegerField(choices=[(0, 'Approved'), (1, 'Pending'), (2, 'Rejected')], default=1, verbose_name='Review status'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='channel',
            field=models.SmallIntegerField(choices=[(0, 'Alipay'), (1, 'Wechat'), (2, 'Card'), (3, 'Qaicash'), (4, 'Asia Pay')], default=2, verbose_name='Channel'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='remark',
            field=models.CharField(blank=True, max_length=200, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Success'), (1, 'Unsuccess')], default=1, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='depositaccessmanagement',
            name='deposit_channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_access_channel', to='accounting.DepositChannel', verbose_name='Channel'),
        ),
        migrations.AddField(
            model_name='depositaccessmanagement',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='use', to=settings.AUTH_USER_MODEL),
        ),
    ]
