# Generated by Django 2.1.7 on 2019-06-28 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0034_merge_20190625_0853'),
        ('accounting', '0033_auto_20190625_1135'),
    ]

    operations = [
    ]
