# Generated by Django 2.1.7 on 2019-07-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_merge_20190628_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'SUCCESS'), (1, 'FAILED'), (2, 'CREATED'), (3, 'PENDING'), (4, 'APPROVED'), (5, 'CANCELED'), (6, 'COMPLETED')], default=2, verbose_name='Status'),
        ),
    ]
