# Generated by Django 2.1.7 on 2019-05-14 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0003_auto_20190514_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='WithdrawAccessManagement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_user', to=settings.AUTH_USER_MODEL)),
                ('withdraw_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_access_channel', to='accounting.WithdrawChannel', verbose_name='Channel')),
            ],
            options={
                'verbose_name': 'Withdraw Access management',
                'verbose_name_plural': 'Withdraw Access management',
            },
        ),
        migrations.AlterField(
            model_name='depositaccessmanagement',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposit_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='depositaccessmanagement',
            unique_together={('user_id', 'deposit_channel')},
        ),
        migrations.AlterUniqueTogether(
            name='withdrawaccessmanagement',
            unique_together={('user_id', 'withdraw_channel')},
        ),
    ]
