# Generated by Django 2.1.7 on 2019-05-16 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_auto_20190514_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositchannel',
            name='method',
            field=models.CharField(blank=True, max_length=30, verbose_name='Method'),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='method',
            field=models.CharField(blank=True, max_length=30, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='depositchannel',
            name='currency',
            field=models.SmallIntegerField(choices=[(0, 'CNY'), (1, 'USD'), (2, 'PHP'), (3, 'IDR')], default=0, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='withdrawchannel',
            name='currency',
            field=models.SmallIntegerField(choices=[(0, 'CNY'), (1, 'USD'), (2, 'PHP'), (3, 'IDR')], default=0, verbose_name='Currency'),
        ),
    ]
