# Generated by Django 2.1.7 on 2019-05-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_auto_20190516_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositchannel',
            name='method',
            field=models.CharField(max_length=30, verbose_name='Method'),
        ),
        migrations.AlterField(
            model_name='withdrawchannel',
            name='method',
            field=models.CharField(max_length=30, verbose_name='Method'),
        ),
    ]
