# Generated by Django 2.1.7 on 2019-05-31 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_auto_20190523_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.SmallIntegerField(choices=[(0, 'Deposit'), (1, 'Withdraw'), (2, 'Bet')], default=0, verbose_name='Transaction Type'),
        ),
    ]
