# Generated by Django 2.1.7 on 2019-06-06 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_auto_20190603_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'SUCCESS'), (1, 'FAILED'), (2, 'PENDING'), (3, 'APPROVED'), (4, 'REJECTED')], default=2, verbose_name='Status'),
        ),
    ]
