# Generated by Django 2.1.7 on 2019-06-10 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_auto_20190609_1618'),
        ('accounting', '0017_auto_20190610_1019'),
    ]

    operations = [
    ]
