# Generated by Django 2.1.7 on 2019-06-13 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_merge_20190610_1358'),
        ('accounting', '0015_auto_20190606_1806'),
    ]

    operations = [
    ]
