# Generated by Django 2.1.7 on 2019-06-14 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0018_merge_20190610_1358'),
        ('accounting', '0020_auto_20190611_2313'),
    ]

    operations = [
    ]
