# Generated by Django 2.1.7 on 2019-06-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0019_auto_20190614_1422'),
        ('accounting', '0022_auto_20190614_1512'),
    ]

    operations = [
    ]
