# Generated by Django 2.1.7 on 2019-06-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_auto_20190619_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='channel',
            field=models.SmallIntegerField(choices=[(0, 'Alipay'), (1, 'LINEpay'), (2, 'Astropay'), (3, 'Qaicash'), (4, 'Asia Pay'), (5, 'Paypal')], default=0, verbose_name='Payment'),
        ),
    ]
