# Generated by Django 2.1.7 on 2019-06-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0026_auto_20190621_1219'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='id',
            new_name='trans_id',
        ),
    ]
