# Generated by Django 2.1.7 on 2019-06-21 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_auto_20190621_1344'),
        ('accounting', '0023_merge_20190620_2235'),
    ]

    operations = [
    ]
