# Generated by Django 2.1.7 on 2019-06-21 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_merge_20190621_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositchannel',
            name='thridParty_name',
            field=models.SmallIntegerField(choices=[(0, 'Xpay'), (1, 'LINEpay'), (2, 'Astropay'), (3, 'Qaicash'), (4, 'Asia Pay'), (5, 'Paypal')], default=2, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='channel',
            field=models.SmallIntegerField(choices=[(0, 'Xpay'), (1, 'LINEpay'), (2, 'Astropay'), (3, 'Qaicash'), (4, 'Asia Pay'), (5, 'Paypal')], default=0, verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='withdrawchannel',
            name='thridParty_name',
            field=models.SmallIntegerField(choices=[(0, 'Xpay'), (1, 'LINEpay'), (2, 'Astropay'), (3, 'Qaicash'), (4, 'Asia Pay'), (5, 'Paypal')], default=2, verbose_name='Name'),
        ),
    ]
