# Generated by Django 2.1.7 on 2019-06-22 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_auto_20190621_1733'),
        ('accounting', '0031_auto_20190621_1637'),
    ]

    operations = [
    ]
