# Generated by Django 2.1.7 on 2019-06-22 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_merge_20190619_1140'),
        ('accounting', '0031_auto_20190621_1637'),
    ]

    operations = [
    ]
