# Generated by Django 2.1.7 on 2019-06-24 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_auto_20190621_1637'),
        ('accounting', '0019_merge_20190613_1210'),
    ]

    operations = [
    ]
