# Generated by Django 2.1.7 on 2019-06-24 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_merge_20190621_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Status Last Updated'),
        ),
    ]
