# Generated by Django 2.1.7 on 2019-06-28 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_auto_20190625_1135'),
        ('accounting', '0033_transaction_last_updated'),
    ]

    operations = [
    ]
