# Generated by Django 2.1.7 on 2019-06-25 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_merge_20190625_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositchannel',
            name='transaction_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Transaction Fee'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'SUCCESS'), (1, 'FAILED'), (2, 'CREATED'), (3, 'PENDING'), (4, 'APPROVED'), (5, 'REJECTED'), (6, 'COMPLETED')], default=2, verbose_name='Status'),
        ),
    ]
