# Generated by Django 2.1.7 on 2019-07-01 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_auto_20190701_1023'),
        ('accounting', '0034_merge_20190628_1432'),
    ]

    operations = [
    ]
