# Generated by Django 2.1.7 on 2019-07-09 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_auto_20190708_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositchannel',
            name='limit_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='limit_access',
            field=models.BooleanField(default=False),
        ),
    ]
