# Generated by Django 2.1.7 on 2019-07-08 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_merge_20190701_1514'),
        ('accounting', '0037_merge_20190701_1413'),
    ]

    operations = [
    ]
