# Generated by Django 2.1.7 on 2019-07-09 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_merge_20190708_1037'),
        ('accounting', '0038_merge_20190708_1042'),
    ]

    operations = [
    ]
