# Generated by Django 2.1.7 on 2019-07-10 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0039_merge_20190708_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'SUCCESS'), (1, 'FAILED'), (2, 'CREATED'), (3, 'PENDING'), (4, 'APPROVED'), (5, 'CANCELED'), (6, 'COMPLETED'), (7, 'RESEND'), (8, 'REJECTED'), (9, 'SUCCESS')], default=2, verbose_name='Status'),
        ),
    ]
