# Generated by Django 2.1.7 on 2019-07-31 00:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0041_auto_20190716_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('bank_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default=0, max_length=200)),
                ('branch', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('city', models.CharField(blank=True, default=0, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='channel',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='payer_id',
        ),
        migrations.AddField(
            model_name='depositchannel',
            name='limit_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='depositchannel',
            name='new_user_volume',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=20),
        ),
        migrations.AddField(
            model_name='depositchannel',
            name='transaction_fee',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Transaction Fee'),
        ),
        migrations.AddField(
            model_name='depositchannel',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='deposit_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.DepositChannel'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_image',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='withdraw_channel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.WithdrawChannel'),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='limit_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='new_user_volume',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=20),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=20),
        ),
        migrations.AlterField(
            model_name='depositchannel',
            name='thridParty_name',
            field=models.SmallIntegerField(choices=[(0, 'Help2pay'), (1, 'LINEpay'), (2, 'Astropay'), (3, 'Qaicash'), (4, 'Asia Pay'), (5, 'Paypal'), (6, 'fgate')], default=2, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.SmallIntegerField(choices=[(0, 'CNY'), (1, 'USD'), (2, 'THB'), (3, 'IDR'), (4, 'HKD'), (5, 'AUD'), (6, 'THB'), (7, 'MYR'), (8, 'VND'), (9, 'MMK'), (10, 'XBT')], default=0, verbose_name='Currency'),
        ),
        migrations.AlterField(
            model_name='withdrawchannel',
            name='thridParty_name',
            field=models.SmallIntegerField(choices=[(0, 'Help2pay'), (1, 'LINEpay'), (2, 'Astropay'), (3, 'Qaicash'), (4, 'Asia Pay'), (5, 'Paypal'), (6, 'fgate')], default=2, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='depositchannel',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Bank'),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.Bank'),
        ),
    ]
