# Generated by Django 2.1.7 on 2019-07-30 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_auto_20190708_1709'),
        ('accounting', '0041_auto_20190716_1516'),
    ]

    operations = [
    ]
