# Generated by Django 2.1.7 on 2019-07-29 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0041_auto_20190716_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositchannel',
            name='thridParty_name',
            field=models.SmallIntegerField(choices=[(0, 'Help2pay'), (1, 'LINEpay'), (2, 'Astropay'), (3, 'Qaicash'), (4, 'Asia Pay'), (5, 'Paypal'), (6, 'fgate')], default=2, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='arrive_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Account Time'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='channel',
            field=models.SmallIntegerField(choices=[(0, 'Help2pay'), (1, 'LINEpay'), (2, 'Astropay'), (3, 'Qaicash'), (4, 'Asia Pay'), (5, 'Paypal'), (6, 'fgate')], default=0, verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'SUCCESS'), (1, 'FAILED'), (2, 'CREATED'), (3, 'PENDING'), (4, 'APPROVED'), (5, 'CANCELED'), (6, 'COMPLETED'), (7, 'RESEND'), (8, 'REJECTED'), (9, 'HELD')], default=2, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='withdrawchannel',
            name='thridParty_name',
            field=models.SmallIntegerField(choices=[(0, 'Help2pay'), (1, 'LINEpay'), (2, 'Astropay'), (3, 'Qaicash'), (4, 'Asia Pay'), (5, 'Paypal'), (6, 'fgate')], default=2, verbose_name='Name'),
        ),
    ]
