# Generated by Django 2.1.7 on 2019-07-31 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0042_auto_20190731_1435'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositchannel',
            name='switch'
        ),
        migrations.RemoveField(
            model_name='withdrawchannel',
            name='switch'
        ),
    ]
