# Generated by Django 2.1.7 on 2019-08-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0042_auto_20190729_1503'),
        ('accounting', '0042_auto_20190808_1002'),
    ]

    operations = [
    ]
