# Generated by Django 2.1.7 on 2019-08-08 17:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0042_auto_20190808_1002'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositchannel',
            name='thirdParty_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='depositchannel',
            name='thirdParty_name',
            field=models.SmallIntegerField(choices=[(0, 'Help2Pay'), (1, 'LINEpay'), (2, 'AstroPay'), (3, 'Qaicash'), (4, 'AsiaPay'), (5, 'Paypal'), (6, 'Payzod'), (7, 'CirclePay'), (8, 'Fgate')], default=2, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='thirdParty_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='thirdParty_name',
            field=models.SmallIntegerField(choices=[(0, 'Help2Pay'), (1, 'LINEpay'), (2, 'AstroPay'), (3, 'Qaicash'), (4, 'AsiaPay'), (5, 'Paypal'), (6, 'Payzod'), (7, 'CirclePay'), (8, 'Fgate')], default=2, verbose_name='Name'),
        ),
    ]
