# Generated by Django 2.1.7 on 2019-08-11 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_auto_20190808_1006'),
        ('accounting', '0042_auto_20190806_1814'),
    ]

    operations = [
    ]
