# Generated by Django 2.1.7 on 2019-07-31 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_auto_20190731_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositchannel',
            name='switch',
            field=models.SmallIntegerField(choices=[(0, 'OPEN'), (1, 'CLOSE')], default=0),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='switch',
            field=models.SmallIntegerField(choices=[(0, 'OPEN'), (1, 'CLOSE')], default=0),
        ),
    ]
