# Generated by Django 2.1.7 on 2019-08-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_auto_20190808_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='arrive_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Account Time'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'SUCCESS'), (1, 'FAILED'), (2, 'CREATED'), (3, 'PENDING'), (4, 'APPROVED'), (5, 'CANCELED'), (6, 'COMPLETED'), (7, 'RESEND'), (8, 'REJECTED'), (9, 'HELD')], default=2, verbose_name='Status'),
        ),
    ]
