# Generated by Django 2.1.7 on 2019-08-01 00:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0044_auto_20190731_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('account_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_name', models.CharField(default=0, max_length=200)),
                ('account_number', models.CharField(default=0, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='depositchannel',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_code',
        ),
        migrations.RemoveField(
            model_name='withdrawchannel',
            name='bank',
        ),
        migrations.AddField(
            model_name='bank',
            name='province',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='depositchannel',
            name='block_risk_level',
            field=models.SmallIntegerField(choices=[(0, 'A'), (1, 'E1'), (2, 'E2'), (3, 'F')], default=0),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='block_risk_level',
            field=models.SmallIntegerField(choices=[(0, 'A'), (1, 'E1'), (2, 'E2'), (3, 'F')], default=0),
        ),
        migrations.AddField(
            model_name='bankaccount',
            name='bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.Bank'),
        ),
    ]
