# Generated by Django 2.1.7 on 2019-08-01 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0045_auto_20190731_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='user_bank_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.BankAccount'),
        ),
    ]
