# Generated by Django 2.1.7 on 2019-08-23 00:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0045_auto_20190816_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositchannel',
            name='channel',
            field=models.CharField(default='Devcode', max_length=30, verbose_name='Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depositchannel',
            name='market',
            field=models.SmallIntegerField(choices=[(0, 'ibet-VN'), (1, 'ibet-TH')], default=0),
        ),
        migrations.AddField(
            model_name='depositchannel',
            name='req_ver',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='depositchannel',
            name='transaction_fee_per',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Transaction Fee Percentage'),
        ),
        migrations.AddField(
            model_name='depositchannel',
            name='vip_level',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'VIP_1'), (2, 'VIP_2'), (3, 'VIP_3'), (4, 'VIP_4'), (5, 'VIP_5'), (6, 'VIP_6')], null=True),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='channel',
            field=models.CharField(default='Devcode', max_length=30, verbose_name='Channel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='market',
            field=models.SmallIntegerField(choices=[(0, 'ibet-VN'), (1, 'ibet-TH')], default=0),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='req_ver',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='transaction_fee_per',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, verbose_name='Transaction Fee Percentage'),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='vip_level',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'VIP_1'), (2, 'VIP_2'), (3, 'VIP_3'), (4, 'VIP_4'), (5, 'VIP_5'), (6, 'VIP_6')], null=True),
        ),
        migrations.AlterField(
            model_name='depositchannel',
            name='block_risk_level',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'A'), (1, 'E1'), (2, 'E2'), (3, 'F')], null=True),
        ),
        migrations.AlterField(
            model_name='depositchannel',
            name='deposit_channel',
            field=models.ManyToManyField(blank=True, related_name='thirdparty', through='accounting.DepositAccessManagement', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='withdrawchannel',
            name='block_risk_level',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'A'), (1, 'E1'), (2, 'E2'), (3, 'F')], null=True),
        ),
    ]
