# Generated by Django 2.1.7 on 2019-08-23 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0046_auto_20190822_1744'),
        ('accounting', '0045_auto_20190819_1625'),
    ]

    operations = [
    ]
