# Generated by Django 2.1.7 on 2019-08-14 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_auto_20190808_1006'),
        ('accounting', '0046_transaction_user_bank_account'),
    ]

    operations = [
    ]
