# Generated by Django 2.1.7 on 2019-08-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0047_merge_20190822_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositchannel',
            name='market',
            field=models.SmallIntegerField(choices=[(0, 'ibet-VN'), (1, 'ibet-TH')]),
        ),
        migrations.AlterField(
            model_name='depositchannel',
            name='switch',
            field=models.SmallIntegerField(choices=[(0, 'ACTIVE'), (1, 'DISABLED')], default=0),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(default=0, max_length=200, verbose_name='Order id'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=0, max_length=200, verbose_name='Transaction id'),
        ),
        migrations.AlterField(
            model_name='withdrawchannel',
            name='market',
            field=models.SmallIntegerField(choices=[(0, 'ibet-VN'), (1, 'ibet-TH')]),
        ),
        migrations.AlterField(
            model_name='withdrawchannel',
            name='switch',
            field=models.SmallIntegerField(choices=[(0, 'ACTIVE'), (1, 'DISABLED')], default=0),
        ),
    ]
