# Generated by Django 2.1.7 on 2019-08-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0045_auto_20190819_1625'),
        ('accounting', '0047_merge_20190814_1059'),
    ]

    operations = [
    ]
