# Generated by Django 2.1.7 on 2019-08-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0048_auto_20190822_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='arrive_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Arrive Time'),
        ),
    ]
