# Generated by Django 2.1.7 on 2019-09-16 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0050_auto_20190830_1509'),
        ('accounting', '0050_auto_20190826_1335'),
    ]

    operations = [
    ]
