# Generated by Django 2.1.7 on 2019-09-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0051_merge_20190916_0948'),
        ('accounting', '0051_auto_20190911_1051'),
    ]

    operations = [
    ]
