# Generated by Django 2.1.7 on 2019-09-17 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0021_merge_20190614_1330'),
        ('accounting', '0051_auto_20190911_1051'),
    ]

    operations = [
    ]
