# Generated by Django 2.1.7 on 2019-09-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0052_merge_20190917_1038'),
        ('accounting', '0051_auto_20190904_1346'),
    ]

    operations = [
    ]
