# Generated by Django 2.1.7 on 2019-09-19 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0143_auto_20190918_1228'),
        ('accounting', '0053_merge_20190917_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='commission_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Commission', verbose_name='Commission'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='month',
            field=models.DateField(null=True),
        ),
    ]
