# Generated by Django 2.1.7 on 2019-09-27 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0053_auto_20190926_1752'),
        ('accounting', '0054_auto_20190926_1812'),
    ]

    operations = [
    ]
