# Generated by Django 2.1.7 on 2019-09-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0054_auto_20190926_1812'),
        ('accounting', '0056_auto_20190924_0859'),
    ]

    operations = [
    ]
