# Generated by Django 2.1.7 on 2019-09-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0057_merge_20190927_1004'),
        ('accounting', '0056_auto_20190927_1051'),
    ]

    operations = [
    ]
