# Generated by Django 2.1.7 on 2019-10-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0058_merge_20190930_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='qrcode',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='QRCode'),
        ),
    ]
