# Generated by Django 2.1.7 on 2019-10-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0059_transaction_qrcode'),
        ('accounting', '0054_remove_transaction_supplier'),
    ]

    operations = [
    ]
