# Generated by Django 2.1.7 on 2019-10-30 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0060_auto_20191029_1531'),
        ('accounting', '0060_auto_20191025_1108'),
    ]

    operations = [
    ]
