# Generated by Django 2.1.7 on 2019-10-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0060_merge_20191022_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositReview',
            fields=[
            ],
            options={
                'verbose_name': 'Deposit Review',
                'verbose_name_plural': 'Deposit Review',
                'proxy': True,
                'indexes': [],
            },
            bases=('accounting.transaction',),
        ),
        migrations.CreateModel(
            name='WithdrawReview',
            fields=[
            ],
            options={
                'verbose_name': 'Withdraw Review',
                'verbose_name_plural': 'Withdraw Review',
                'proxy': True,
                'indexes': [],
            },
            bases=('accounting.transaction',),
        ),
        migrations.AlterField(
            model_name='depositchannel',
            name='supplier',
            field=models.CharField(max_length=50, null=True, verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='remark',
            field=models.CharField(blank=True, max_length=200, verbose_name='Memo'),
        ),
        migrations.AlterField(
            model_name='withdrawchannel',
            name='supplier',
            field=models.CharField(max_length=50, null=True, verbose_name='Supplier'),
        ),
    ]
