# Generated by Django 2.1.7 on 2019-10-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0061_auto_20191022_1704'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DepositReview',
        ),
        migrations.DeleteModel(
            name='WithdrawReview',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Successful'), (1, 'Failed'), (2, 'Created'), (3, 'Pending'), (4, 'Approved'), (5, 'Canceled'), (6, 'Completed'), (7, 'Resent'), (8, 'Rejected'), (9, 'Held')], default=2, verbose_name='Status'),
        ),
    ]
