# Generated by Django 2.1.7 on 2019-10-31 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0062_auto_20191028_1558'),
        ('accounting', '0060_auto_20191025_1108'),
    ]

    operations = [
    ]
