# Generated by Django 2.1.7 on 2019-11-06 23:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0064_auto_20191104_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='other_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='order_id',
            field=models.CharField(default=0, max_length=200, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(default=0, max_length=200, verbose_name='Transaction ID'),
        ),
    ]
