# Generated by Django 2.1.7 on 2019-11-07 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0065_depositaccessmanagement_deposit_favorite_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='depositaccessmanagement',
            name='deposit_favorite_method',
        ),
    ]
