# Generated by Django 2.1.7 on 2019-11-13 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0066_remove_depositaccessmanagement_deposit_favorite_method'),
        ('accounting', '0063_merge_20191031_1520'),
    ]

    operations = [
    ]
