# Generated by Django 2.1.7 on 2019-11-15 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0068_auto_20191113_1927'),
        ('accounting', '0068_auto_20191113_1724'),
    ]

    operations = [
    ]
