# Generated by Django 2.1.7 on 2019-12-03 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0065_auto_20191106_1545'),
        ('accounting', '0069_merge_20191115_1518'),
    ]

    operations = [
    ]
