# Generated by Django 2.1.7 on 2019-12-03 22:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0070_auto_20191202_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='depositchannel',
            old_name='vip_level',
            new_name='player_segment',
        ),
        migrations.RenameField(
            model_name='withdrawchannel',
            old_name='vip_level',
            new_name='player_segment',
        ),
        migrations.AddField(
            model_name='depositchannel',
            name='changelog',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='changelog',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='depositchannel',
            name='market',
            field=models.SmallIntegerField(choices=[(0, 'ibet-VN'), (1, 'ibet-TH'), (2, 'ibet-CN'), (3, 'letou-VN'), (4, 'letou-TH'), (5, 'letou-CN')]),
        ),
        migrations.AlterField(
            model_name='depositchannel',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Disabled')], default=0),
        ),
        migrations.AlterField(
            model_name='withdrawchannel',
            name='market',
            field=models.SmallIntegerField(choices=[(0, 'ibet-VN'), (1, 'ibet-TH'), (2, 'ibet-CN'), (3, 'letou-VN'), (4, 'letou-TH'), (5, 'letou-CN')]),
        ),
        migrations.AlterField(
            model_name='withdrawchannel',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'Active'), (1, 'Disabled')], default=0),
        ),
    ]
