# Generated by Django 2.1.7 on 2019-12-03 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0071_auto_20191203_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user_bank_account',
        ),
    ]
