# Generated by Django 2.1.7 on 2019-12-03 23:07

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0072_remove_transaction_user_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bank_info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict, null=True),
        ),
    ]
