# Generated by Django 2.1.7 on 2019-12-04 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0070_merge_20191203_1549'),
        ('accounting', '0073_transaction_bank_info'),
    ]

    operations = [
    ]
