# Generated by Django 2.1.7 on 2019-12-12 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0072_auto_20191205_1625'),
        ('accounting', '0074_merge_20191203_1602'),
    ]

    operations = [
    ]
