# Generated by Django 2.1.7 on 2019-12-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0075_merge_20191211_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositchannel',
            name='market',
            field=models.SmallIntegerField(choices=[(0, 'ibet-VN'), (1, 'ibet-TH'), (2, 'ibet-CN'), (3, 'letou-VN'), (4, 'letou-TH'), (5, 'letou-CN')]),
        ),
        migrations.AlterField(
            model_name='depositchannel',
            name='thirdParty_name',
            field=models.SmallIntegerField(choices=[(0, 'Help2Pay'), (1, 'LINEpay'), (2, 'AstroPay'), (3, 'Qaicash'), (4, 'AsiaPay'), (5, 'Paypal'), (6, 'Payzod'), (7, 'CirclePay'), (8, 'Fgate'), (9, 'ScratchCard'), (10, 'PaymentIQ'), (11, 'Local Bank Transfer')], default=2, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='channel',
            field=models.SmallIntegerField(choices=[(0, 'Help2Pay'), (1, 'LINEpay'), (2, 'AstroPay'), (3, 'Qaicash'), (4, 'AsiaPay'), (5, 'Paypal'), (6, 'Payzod'), (7, 'CirclePay'), (8, 'Fgate'), (9, 'ScratchCard'), (10, 'PaymentIQ'), (11, 'Local Bank Transfer')], default=0, verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='withdrawchannel',
            name='market',
            field=models.SmallIntegerField(choices=[(0, 'ibet-VN'), (1, 'ibet-TH'), (2, 'ibet-CN'), (3, 'letou-VN'), (4, 'letou-TH'), (5, 'letou-CN')]),
        ),
        migrations.AlterField(
            model_name='withdrawchannel',
            name='thirdParty_name',
            field=models.SmallIntegerField(choices=[(0, 'Help2Pay'), (1, 'LINEpay'), (2, 'AstroPay'), (3, 'Qaicash'), (4, 'AsiaPay'), (5, 'Paypal'), (6, 'Payzod'), (7, 'CirclePay'), (8, 'Fgate'), (9, 'ScratchCard'), (10, 'PaymentIQ'), (11, 'Local Bank Transfer')], default=2, verbose_name='Name'),
        ),
    ]
