# Generated by Django 2.1.7 on 2019-12-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0076_auto_20191212_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositchannel',
            name='result_override',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='depositchannel',
            name='risk_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='depositchannel',
            name='settlement_confirmation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='result_override',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='risk_review',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='settlement_confirmation',
            field=models.BooleanField(default=True),
        ),
    ]
