# Generated by Django 2.1.7 on 2019-12-13 23:42

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0077_auto_20191213_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositchannel',
            name='all_downtime',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='all_downtime',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
