# Generated by Django 2.1.15 on 2020-01-08 19:17

import accounting.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0078_auto_20191213_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositchannel',
            name='all_downtime',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=accounting.models.defaultDowntime, null=True),
        ),
        migrations.AlterField(
            model_name='withdrawchannel',
            name='all_downtime',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=accounting.models.defaultDowntime, null=True),
        ),
    ]
