# Generated by Django 2.1.15 on 2020-01-08 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0079_auto_20200108_1117'),
        ('accounting', '0077_auto_20200108_1501'),
    ]

    operations = [
    ]
