# Generated by Django 2.1.7 on 2020-01-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0079_auto_20200108_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositchannel',
            name='allowed_statuses',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'ALL'), (2, 'NORMAL')], null=True),
        ),
        migrations.AddField(
            model_name='withdrawchannel',
            name='allowed_statuses',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'ALL'), (2, 'NORMAL')], null=True),
        ),
    ]
