# Generated by Django 2.1.7 on 2020-01-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0082_auto_20200109_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=4, max_digits=20, verbose_name='Apply Amount'),
        ),
    ]
