# Generated by Django 2.1.15 on 2020-01-14 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0083_auto_20200110_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='product',
            field=models.SmallIntegerField(choices=[(0, 'Sports'), (1, 'Games'), (2, 'Live Casino'), (3, 'Table Games'), (4, 'General'), (5, 'Lottory')], default=4, verbose_name='Product'),
        ),
    ]
