# Generated by Django 2.1.7 on 2020-01-11 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0080_auto_20200108_1606'),
        ('accounting', '0083_auto_20200110_1146'),
    ]

    operations = [
    ]
