# Generated by Django 2.1.7 on 2020-01-21 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0084_merge_20200110_1702'),
        ('accounting', '0084_auto_20200113_2259'),
    ]

    operations = [
    ]
