# Generated by Django 2.1.7 on 2020-01-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0084_auto_20200113_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='current_balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=20, verbose_name='Current Balance'),
        ),
    ]
