# Generated by Django 2.1.7 on 2020-02-01 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0085_transaction_current_balance'),
        ('accounting', '0085_merge_20200121_1503'),
    ]

    operations = [
    ]
