# Generated by Django 2.1.7 on 2020-02-11 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0086_merge_20200131_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositchannel',
            name='thirdParty_name',
            field=models.SmallIntegerField(choices=[(0, 'Help2Pay'), (1, 'LINEpay'), (2, 'AstroPay'), (3, 'Qaicash'), (4, 'AsiaPay'), (5, 'Paypal'), (6, 'Payzod'), (7, 'CirclePay'), (8, 'Fgate'), (9, 'ScratchCard'), (10, 'PaymentIQ'), (11, 'Local Bank Transfer'), (12, 'MoMo Pay')], default=2, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='channel',
            field=models.SmallIntegerField(choices=[(0, 'Help2Pay'), (1, 'LINEpay'), (2, 'AstroPay'), (3, 'Qaicash'), (4, 'AsiaPay'), (5, 'Paypal'), (6, 'Payzod'), (7, 'CirclePay'), (8, 'Fgate'), (9, 'ScratchCard'), (10, 'PaymentIQ'), (11, 'Local Bank Transfer'), (12, 'MoMo Pay')], null=True, verbose_name='Payment'),
        ),
        migrations.AlterField(
            model_name='withdrawchannel',
            name='thirdParty_name',
            field=models.SmallIntegerField(choices=[(0, 'Help2Pay'), (1, 'LINEpay'), (2, 'AstroPay'), (3, 'Qaicash'), (4, 'AsiaPay'), (5, 'Paypal'), (6, 'Payzod'), (7, 'CirclePay'), (8, 'Fgate'), (9, 'ScratchCard'), (10, 'PaymentIQ'), (11, 'Local Bank Transfer'), (12, 'MoMo Pay')], default=2, verbose_name='Name'),
        ),
    ]
