# Generated by Django 2.1.15 on 2020-02-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0086_merge_20200131_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='depositchannel',
            name='block_risk_level',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Very High'), (1, 'High'), (2, 'Medium'), (3, 'Low'), (4, 'Very Low'), (5, 'VIP'), (6, 'Business')], null=True),
        ),
        migrations.AlterField(
            model_name='withdrawchannel',
            name='block_risk_level',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'Very High'), (1, 'High'), (2, 'Medium'), (3, 'Low'), (4, 'Very Low'), (5, 'VIP'), (6, 'Business')], null=True),
        ),
    ]
