# Generated by Django 2.1.15 on 2020-02-14 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0087_auto_20200210_1408'),
        ('accounting', '0087_auto_20200210_1600'),
    ]

    operations = [
    ]
