# Generated by Django 2.1.7 on 2019-07-30 01:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0002_auto_20190418_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('bonus_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField(verbose_name='Start Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('expiration_days', models.IntegerField()),
                ('is_valid', models.BooleanField(default=False)),
                ('countries', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('percentage', models.FloatField()),
                ('coupon_code', models.CharField(max_length=50)),
                ('is_free_bid', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BonusCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus.Bonus', verbose_name='Bonus')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Category', verbose_name='Category')),
            ],
        ),
        migrations.CreateModel(
            name='BonusRequirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus.Bonus', verbose_name='Bonus')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('requirement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('field_name', models.SmallIntegerField(choices=[(0, 'Deposit'), (1, 'Withdrawal'), (2, 'Bet Placed'), (3, 'Bet Settled'), (4, 'Transfer In'), (5, 'Transfer Out'), (6, 'Bonus'), (7, 'Adjustment'), (8, 'Commission')], default=0, verbose_name='Transaction Type')),
                ('aggregate_method', models.CharField(max_length=50)),
                ('time_limit', models.IntegerField()),
                ('turnover_multiplier', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RequirementCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Category', verbose_name='Category')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus.Requirement', verbose_name='Requirement')),
            ],
        ),
        migrations.AddField(
            model_name='bonusrequirement',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus.Requirement', verbose_name='Requirement'),
        ),
    ]
