# Generated by Django 2.1.7 on 2019-10-03 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('operation', '0052_remove_notification_bonus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonus', '0004_auto_20190927_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBonusEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Start Time')),
                ('status', models.SmallIntegerField(choices=[(0, 'STARTED'), (1, 'ACTIVE'), (2, 'COMPLETED'), (3, 'EXPIRED')], default=0, verbose_name='User Bonus Event Type')),
                ('notes', models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userbonus',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='userbonus',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bonus',
            name='is_valid',
        ),
        migrations.AddField(
            model_name='bonus',
            name='affiliate_limit',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='operation.Campaign'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='release_type',
            field=models.SmallIntegerField(choices=[(0, 'Pre-wager'), (1, 'Post-wager')], default=0, verbose_name='Bonus Release Type'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'INACTIVE'), (1, 'ACTIVE'), (2, 'DISABLED')], default=0, verbose_name='Bonus Type'),
        ),
        migrations.AddField(
            model_name='bonus',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'VERIFICATION'), (1, 'DEPOSIT'), (2, 'TURNOVER'), (3, 'STANDARD'), (4, 'FREE SPINS')], default=0, verbose_name='Bonus Type'),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='amount',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='turnover_multiplier',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='UserBonus',
        ),
        migrations.AddField(
            model_name='userbonusevents',
            name='bonus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus.Bonus', verbose_name='Bonus'),
        ),
        migrations.AddField(
            model_name='userbonusevents',
            name='delivered_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Operator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userbonusevents',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
