# Generated by Django 2.1.7 on 2019-10-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0005_auto_20191002_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='image_s3',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
