# Generated by Django 2.1.7 on 2019-10-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0006_bonus_image_s3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='affiliate_limit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='image_s3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='percentage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
