# Generated by Django 2.1.7 on 2019-10-06 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0007_auto_20191005_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='aggregate_method',
            field=models.SmallIntegerField(blank=True, choices=[(0, 'SUM'), (1, 'COUNT'), (2, 'AVERAGE'), (3, 'MAX'), (4, 'LATEST')], null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='time_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='turnover_multiplier',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbonusevents',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
