# Generated by Django 2.1.7 on 2019-10-06 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0008_auto_20191005_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonusrequirement',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='bonusrequirement',
            name='requirement',
        ),
        migrations.AddField(
            model_name='requirement',
            name='bonus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bonus.Bonus', verbose_name='Bonus'),
        ),
        migrations.DeleteModel(
            name='BonusRequirement',
        ),
    ]
