# Generated by Django 2.1.7 on 2019-10-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0009_auto_20191006_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='amount_threshold',
            field=models.FloatField(default=0),
        ),
    ]
