# Generated by Django 2.1.7 on 2019-10-13 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonus', '0010_requirement_amount_threshold'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBonusEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='Start Time')),
                ('status', models.SmallIntegerField(choices=[(0, 'STARTED'), (1, 'ACTIVE'), (2, 'COMPLETED'), (3, 'EXPIRED')], default=0, verbose_name='User Bonus Event Type')),
                ('notes', models.TextField(blank=True, null=True)),
                ('bonus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus.Bonus', verbose_name='Bonus')),
                ('delivered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Operator', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='userbonusevents',
            name='bonus',
        ),
        migrations.RemoveField(
            model_name='userbonusevents',
            name='delivered_by',
        ),
        migrations.RemoveField(
            model_name='userbonusevents',
            name='owner',
        ),
        migrations.DeleteModel(
            name='UserBonusEvents',
        ),
    ]
