# Generated by Django 2.1.7 on 2019-10-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0011_auto_20191012_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='currency',
            field=models.SmallIntegerField(choices=[(0, 'CNY'), (1, 'USD'), (2, 'THB'), (3, 'IDR'), (4, 'HKD'), (5, 'AUD'), (6, 'MYR'), (7, 'VND'), (8, 'MMK'), (9, 'XBT'), (10, 'EUR'), (11, 'NOK'), (12, 'GBP')], default=0, verbose_name='Bonus Currency'),
        ),
        migrations.AddField(
            model_name='userbonusevent',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
