# Generated by Django 2.1.7 on 2019-10-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0012_auto_20191024_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbonusevent',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'STARTED'), (1, 'ACTIVE'), (2, 'COMPLETED'), (3, 'EXPIRED'), (4, 'ISSUED'), (5, 'REDEEMED')], default=0, verbose_name='User Bonus Event Type'),
        ),
    ]
