# Generated by Django 2.1.7 on 2019-10-30 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0012_auto_20191029_1531'),
        ('bonus', '0013_auto_20191028_0934'),
    ]

    operations = [
    ]
