# Generated by Django 2.1.7 on 2019-11-07 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0012_auto_20191016_1432'),
        ('bonus', '0017_auto_20191104_1329'),
    ]

    operations = [
    ]
