# Generated by Django 2.1.7 on 2019-12-03 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_auto_20191031_1411'),
        ('bonus', '0018_merge_20191107_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusUserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='bonus',
            name='category',
            field=models.SmallIntegerField(choices=[(0, 'Manual'), (1, 'Triggered')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='delivery',
            field=models.SmallIntegerField(choices=[(0, 'Push'), (1, 'Site activation')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='issued',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='max_daily_times',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='max_relevant_times',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='max_total_times',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='bonus',
            name='max_users',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requirement',
            name='must_have',
            field=models.SmallIntegerField(choices=[(0, 'ID verified'), (1, 'Phone verified'), (2, 'Email verified'), (3, 'A successful deposit'), (4, 'A successful withdrawal'), (5, 'Manual audit for first withdrawal')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='field_name',
            field=models.SmallIntegerField(choices=[(0, 'Deposit'), (1, 'Withdrawal'), (2, 'Bet Placed'), (3, 'Bet Settled'), (4, 'Transfer'), (5, 'Bonus'), (6, 'Adjustment'), (7, 'Commission')], default=0, null=True, verbose_name='Transaction Type'),
        ),
        migrations.AddField(
            model_name='bonususergroup',
            name='bonus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bonus.Bonus', verbose_name='Bonus'),
        ),
        migrations.AddField(
            model_name='bonususergroup',
            name='groups',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='system.UserGroup'),
        ),
    ]
