# Generated by Django 2.1.7 on 2019-12-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0019_auto_20191203_1338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='release_type',
        ),
        migrations.AlterField(
            model_name='bonus',
            name='countries',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='expiration_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bonus',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'VERIFICATION'), (1, 'DEPOSIT'), (2, 'TURNOVER'), (3, 'STANDARD'), (4, 'FREE SPINS')], default=0, null=True, verbose_name='Bonus Type'),
        ),
    ]
