# Generated by Django 2.1.7 on 2019-12-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0020_auto_20191203_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='type',
            field=models.SmallIntegerField(choices=[(0, 'VERIFICATION'), (1, 'DEPOSIT'), (2, 'TURNOVER'), (3, 'STANDARD'), (4, 'FREE SPINS'), (5, 'MANUAL')], default=0, verbose_name='Bonus Type'),
        ),
    ]
