# Generated by Django 2.1.7 on 2019-12-05 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0022_auto_20191204_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='category',
        ),
    ]
