# Generated by Django 2.1.7 on 2019-12-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0024_auto_20191205_1031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbonusevent',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='userbonusevent',
            name='completion_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbonusevent',
            name='delivery_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
