# Generated by Django 2.1.7 on 2019-12-18 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0025_auto_20191212_1543'),
        ('bonus', '0025_auto_20191213_1121'),
    ]

    operations = [
    ]
