# Generated by Django 2.1.7 on 2019-12-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0026_merge_20191217_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='status',
            field=models.SmallIntegerField(choices=[(0, 'INACTIVE'), (1, 'ACTIVE'), (2, 'DISABLED')], default=0, verbose_name='Bonus Status'),
        ),
    ]
