# Generated by Django 2.1.7 on 2019-12-24 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0027_auto_20191217_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbonusevent',
            name='completion_percentage',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
