# Generated by Django 2.1.7 on 2020-01-07 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0027_auto_20191217_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbonusevent',
            name='status',
            field=models.SmallIntegerField(choices=[(6, 'ISSUED'), (1, 'CLAIMED'), (2, 'ACTIVE'), (3, 'COMPLETED'), (4, 'EXPIRED'), (5, 'CANCELLED'), (6, 'ISSUED'), (7, 'PENDING'), (8, 'RELEASED')], default=0, verbose_name='User Bonus Event Type'),
        ),
    ]
