# Generated by Django 2.1.7 on 2020-01-10 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0029_auto_20200108_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bonus',
            name='max_user_amount',
        ),
    ]
