# Generated by Django 2.1.7 on 2020-01-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0031_auto_20200116_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='bonus',
            name='release_type',
            field=models.SmallIntegerField(choices=[(0, 'Pre-wager'), (1, 'Post-wager')], default=0, verbose_name='Bonus Release Type'),
        ),
    ]
