# Generated by Django 2.1.7 on 2020-01-22 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0032_bonus_release_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='must_have',
            field=models.SmallIntegerField(choices=[(0, 'ID verified'), (1, 'Phone verified'), (2, 'Email verified'), (3, 'A successful deposit'), (4, 'A successful withdrawal'), (5, 'Manual audit for first withdrawal')], null=True),
        ),
    ]
