# Generated by Django 2.1.15 on 2020-02-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonus', '0033_auto_20200121_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonus',
            name='end_time',
            field=models.DateTimeField(null=True, verbose_name='End Time'),
        ),
    ]
